#ifndef LGWHEELS_H
#define LGWHEELS_H

// No idea where this file belongs, it's part of JSystem however no other games seem to have this

class LGWheels
{ // Autogenerated
public:
    // Global
    LGWheels();                                                                       // 0x8007649c
    void InitVars(long);                                                              // 0x80076520
    void ReadAll();                                                                   // 0x80076590
    void StopForce(long, long);                                                       // 0x8007664c
    bool IsConnected(long);                                                           // 0x800769dc
    void IsPlaying(long, long);                                                       // 0x80076a00
    void PlayAutoCalibAndSpringForce(long);                                           // 0x80076b3c
    void PlaySpringForce(long, char, unsigned char, short);                           // 0x80076c74
    void SameSpringForceParams(long, char, unsigned char, short);                     // 0x80076e98
    void PlayConstantForce(long, short, unsigned short);                              // 0x80076ee0
    void SameConstantForceParams(long, short, unsigned short);                        // 0x800770d8
    void PlayDamperForce(long, short);                                                // 0x8007710c
    void SameDamperForceParams(long, short);                                          // 0x80077310
    void PlayDirtRoadEffect(long, unsigned char);                                     // 0x80077330
    void SameDirtRoadEffectParams(long, short);                                       // 0x80077560
    void PlayBumpyRoadEffect(long, unsigned char);                                    // 0x80077580
    void StopBumpyRoadEffect(long);                                                   // 0x800777b0
    void SameBumpyRoadEffectParams(long, short);                                      // 0x800777d4
    void PlaySlipperyRoadEffect(long, short);                                         // 0x800777f4
    void StopSlipperyRoadEffect(long);                                                // 0x80077a90
    void SameSlipperyRoadEffectParams(long, short);                                   // 0x80077ab4
    void PlaySurfaceEffect(long, unsigned char, unsigned char, unsigned short);       // 0x80077ad4
    void SameSurfaceEffectParams(long, unsigned char, unsigned char, unsigned short); // 0x80077e20
    void PlayCarAirborne(long);                                                       // 0x80077e64
    void StopCarAirborne(long);                                                       // 0x8007804c
    // Inline/Unused
    // void ~LGWheels();
    // void ButtonTriggered(long, unsigned long);
    // void ButtonReleased(long, unsigned long);
    // void ButtonIsPressed(long, unsigned long);
    // void PedalsConnected(long);
    // void PowerConnected(long);
    // void SetOverallForceGain(long, long);
    // void GetOverallForceGain(long);
    // void GenerateNonLinValues(long, unsigned char);
    // void StopSpringForce(long);
    // void StopConstantForce(long);
    // void StopDamperForce(long);
    // void PlaySideCollisionForce(long, short, unsigned short);
    // void SameSideCollisionForceParams(long, short, unsigned short);
    // void PlayFrontalCollisionForce(long, unsigned char);
    // void SameFrontalCollisionForceParams(long, short);
    // void StopDirtRoadEffect(long);
    // void StopSurfaceEffect(long);
};     // class LGWheels
#endif // LGWHEELS_H
