#include "Kaneshige/KartInfo.h"

KartInfo::KartInfo() {
    reset();
}

KartInfo::KartCharacter::~KartCharacter() { 
    // destructor gets autogenerated
}

KartInfo::KartCharacter::KartCharacter() {
    reset();
}

void KartInfo::KartCharacter::reset() {
    kartGamePad = 0;
    charDB = 0;
}

void KartInfo::reset() {
    kartDB = 0;
    s32 charCount = 2;
    for (s32 i = 0; i < charCount; i++) {
        kartCharacter[i].reset();
    }
    kartType = 0;
}

KartInfo::~KartInfo() { 
    // destructor gets autogenerated
}