#ifndef CHARACTERSOUNDMGR_H
#define CHARACTERSOUNDMGR_H

#include "types.h"
#include "kartEnums.h"
#include "Inagaki/SoundMgr.h"

namespace GameAudio 
{
class CharacterSoundMgr : public SoundMgr<CharacterSoundMgr>
{ // Autogenerated
public:
    CharacterSoundMgr(Vec *, JKRHeap *, unsigned char, ECharID); // 0x80118d1c
    void init();                                                 // 0x80118e50
    void loop();                                                 // 0x80118ea8
    void frameWork(float, float);                                // 0x80118f48
    void setVoice(unsigned char);                                // 0x80118fb0
    void setSe(unsigned long);                                   // 0x801195e0
    void isSpeak();                                              // 0x80119774
    void setVoicePitch(bool);                                    // 0x80119800
    void getKartSound();                                         // 0x80119980
    void checkEcho();                                            // 0x801199d8
    // Inline/Unused
    // void JASGlobalInstance<JAWSpeAna>::sInstance;
    // void JASGlobalInstance<JAWSeqEdit>::sInstance;
    // Inline
    virtual ~CharacterSoundMgr(); // 0x80118df0
};                                           // class CharacterSoundMgr
}
#endif