#ifndef GAMEMAPSOUNDMGR_H
#define GAMEMAPSOUNDMGR_H

#include "Inagaki/GameSoundMgr.h"

namespace GameAudio {

class CoasterSoundMgr : public SoundWithEchoMgr<CoasterSoundMgr> {
public:
    CoasterSoundMgr(Vec *, JKRHeap *); // 0x8012ec34
    ~CoasterSoundMgr(); // 0x8012ec94
    void frameWork(float); // 0x8012ecf4
    void setEngineSound(float); // 0x8012ed60
    void checkScream(float); // 0x8012ee54
private:
    f32 _68;
    u8 _6c;
    u32 _70;
};

class MapSoundObjectMgr : public SoundWithEchoMgr<MapSoundObjectMgr> { // Autogenerated
public:
    enum Type {
        MapSound_Type0,
        MapSound_Type1,
        MapSound_Type2,
        MapSound_Type3,
        MapSound_Type4,
        MapSound_Type5,
        MapSound_Type6,
        MapSound_Type7,
        MapSound_Type8,
        MapSound_Type9,
        MapSound_Type10,
        MapSound_Type11,
        MapSound_Type12,
        MapSound_Type13,
        MapSound_Type14,
        MapSound_Type15,
        MapSound_Type16,
    };

    MapSoundObjectMgr(Vec *, Type, JKRHeap *); // 0x8012f6c8
    void frameWork(); // 0x8012f788
    int getPlayerGoalRank(); // 0x8012fb20
    // Inline
    virtual ~MapSoundObjectMgr(); // 0x8012f728

private:
    u8 _68;
    Type mType;
}; // class MapSoundObjectMgr

}

#endif
