#ifndef CARDAGENT_H
#define CARDAGENT_H

#include "JSystem/JKernel/JKRHeap.h"

namespace CardAgent
{ // Autogenerated
    // Global
    enum Command {

    };

    void create(JKRHeap *);  // 0x80202a80
    void ask(Command, long); // 0x80202ad4
    void draw();             // 0x80202cc0
    void calc();             // 0x80202d08
    void waitMessage();      // 0x80202de0
    void waitButton();       // 0x80202f00
    void waitSelect();       // 0x80203010
    void check0();           // 0x802033c8
    void waitMount();        // 0x80203508
    void waitCheck();        // 0x80203674
    void waitFormat();       // 0x8020380c
    void checkFree();        // 0x80203944
    void open();             // 0x80203a6c
    void waitCreate();       // 0x80203d48
    void waitWrite();        // 0x80203f6c
    void waitRead();         // 0x802041a8
    void waitRename();       // 0x80204564
    void waitDelete();       // 0x80204708
    void waitSetStatus();    // 0x8020485c
    void waitQuit();         // 0x80204b70
    void reset();            // 0x80204c00
    void isGhostSavable();   // 0x80204c18
    void errorNoCard();      // 0x80204ca8
    void errorWrongDevice(); // 0x80204d68
    void errorIOError();     // 0x80204e28
    void errorEncoding();    // 0x80204eec
    //void msMessageTimer;     // 0x80400cc0
    //void msCommand;          // 0x804169d0
    //void msState;            // 0x804169d4
    //void msSelectAt;         // 0x804169d8
    //void msButtonAt;         // 0x804169dc
    //void msMessageAt;        // 0x804169e0
    //void msResult;           // 0x804169e4
    //void msChan;             // 0x804169e8
    //void mspSaveFile;        // 0x804169ec
    //void mspSystemFile;      // 0x804169f0
    //void mspGhostFile;       // 0x804169f4
    //void msFlags;            // 0x804169f8
    //void mspPrintMemoryCard; // 0x804169fc
    // Inline/Unused
    // void msDrawFlag;
};     // namespace CardAgent
#endif // CARDAGENT_H