#ifndef CARDMGR_H
#define CARDMGR_H

#include "Osako/SaveFile.h"

namespace CardMgr
{ // Autogenerated
    // Global
    void create();                        // 0x802016e0
    void probe();                         // 0x8020175c
    void mount(long);                     // 0x80201800
    void mountTask(void *);               // 0x80201914
    void check(long);                     // 0x802019d8
    void checkTask(void *);               // 0x80201a90
    void format(long);                    // 0x80201b34
    void formatTask(void *);              // 0x80201b94
    void openFile(long, SaveFile *);      // 0x80201c0c
    void createFile(long, SaveFile *);    // 0x80201d88
    void createTask(void *);              // 0x80201e54
    void read(long, SaveFile::FilePart);  // 0x80201f60
    void readTask(void *);                // 0x80202090
    void write(long, SaveFile::FilePart); // 0x80202150
    void writeTask(void *);               // 0x8020231c
    void setStatus(long);                 // 0x80202400
    void setStatusTask(void *);           // 0x802024c0
    void renameFile(long);                // 0x8020269c
    void renameTask(void *);              // 0x8020275c
    void deleteFile(long);                // 0x80202800
    void deleteTask(void *);              // 0x802028c0
    void closeFile(long);                 // 0x80202990
    void unmount(long);                   // 0x80202a10
    //void msaCardData;                   // 0x80400b68
    //void msProbeSlot;                   // 0x804169c8
}; // namespace CardMgr
#endif // CARDMGR_H