#ifndef ERRORVIEWAPP_H
#define ERRORVIEWAPP_H

#include "Kameda/PrintDvdError.h"
#include "Osako/GameApp.h"

class ErrorViewApp : public GameApp
{ // Autogenerated
  // Global
public:
    enum ErrorId
    {
        ERROR_NONE,
        ERROR_COVER_OPEN,
        ERROR_NO_DISK,
        ERROR_WRONG_DISK,
        ERROR_RETRY, // game disk could not be read
        ERROR_FATAL,
        ERROR_LA_TRANSFER,
        ERROR_LA_TRANSFER2,
        ERROR_LA_ROUTER,
        ERROR_LA_CONNECTED,  // check if only gamecubes are connected to lan link
        ERROR_LA_CONNECTION, // check lan cable connection and settings
        ERROR_LA_DISCONNECT,
        ERROR_LA_DISCONNECT_LINK,
    };

    static ErrorViewApp *create(); // 0x802011cc
    static void call(ErrorId);     // 0x8020121c
    ErrorViewApp();                // 0x80201310
    virtual ~ErrorViewApp();       // 0x80201384, override
    virtual void draw();           // 0x802013e4, override
    virtual void calc();           // 0x80201408, override
    virtual void reset();          // 0x802015a8, override

    static ErrorViewApp *mspErrorViewApp; // 0x804169c0
    static ErrorId msErrorId;             // 0x804169c4

    int mErrorState;
    u8 _10[0x18 - 0x10];
    PrintDvdError *mDvdError;
};     // Size: 0x1c
#endif // ERRORVIEWAPP_H