#ifndef FONTMGR_H
#define FONTMGR_H

#include "JSystem/JKernel/JKRHeap.h"
#include "JSystem/JUtility/JUTFont.h"

namespace FontMgr
{ // Autogenerated
    // Global
    void create(JKRHeap *);          // 0x80201134
    extern JUTResFont *mspResFont;   // 0x804169b8
    extern JUTResFont *mspDebugFont; // 0x804169bc
}; // namespace FontMgr
#endif // FONTMGR_H