#ifndef KART2DCOMMON_H
#define KART2DCOMMON_H

#include <JSystem/J2D/J2DPicture.h>
#include <JSystem/JKernel/JKRHeap.h>

#include "kartEnums.h"

// TODO: rename stuff, all textures are probably const, inlines

class Kart2DCommon
{ // Autogenerated
public:
    enum NumberTextureID
    {
        Number_0,
        Number_1,
        Number_2,
        Number_3,
        Number_4,
        Number_5,
        Number_6,
        Number_7,
        Number_8,
        Number_9,
    };

    void changeNumberTexture(int num, J2DPicture **paPicture, u8 places, bool, bool); // 0x8020edd0
    ResTIMG *getAsciiTexture(char);                                                   // 0x8020ef24
    void changeStringTexture(const char *aString, J2DPicture **paPicture, u8 places); // 0x8020effc
    Kart2DCommon();                                                                   // 0x8020f158
    virtual ~Kart2DCommon() { mspKart2DCommon = nullptr; }                            // 0x8020f48c

    static void create(JKRHeap *heap)
    {
        if (mspKart2DCommon == nullptr)
            mspKart2DCommon = new (heap, 0) Kart2DCommon();
    }

    ResTIMG *getNumberTexture(NumberTextureID id) { return mNumberTex[id]; }
    ResTIMG *getCupIconTexture(ERaceGpCup cup) { return mCupIconTex[cup]; }
    ResTIMG *getCupNameTexture(ERaceGpCup cup) { return mCupNameTex[cup]; }

    static Kart2DCommon *ptr() { return mspKart2DCommon; }
private:
    static Kart2DCommon *mspKart2DCommon; // 0x80416a70
    ResTIMG *mNumberTex[11];              // 0 to 9, also why are there 11?
    ResTIMG *mFontData[26];               // chars A to Z
    ResTIMG *mCharIconTex[cCharIDMax - 1]; 
    ResTIMG *mKartIconTex[cKartIDMax];
    ResTIMG *mPartName[4];
    ResTIMG *mPartsLocName[1];
    ResTIMG *mPosImg[8];
    ResTIMG *mCupNameTex[CUP_MAX];
    ResTIMG *mCupIconTex[CUP_MAX];
    ResTIMG *mBattleIconTex[3];
    ResTIMG *mMark[5];
    ResTIMG *mAlphaTex;
}; // Size:0x1bc

extern const char *cpaCharName[20];
extern const char *cpaKartName[21];
extern const char *cpaPartsName[4];
extern const char *cpaCupName[5];
extern const char *cpaCupIcon[5];
extern const char *cpaBattleIcon[3];
extern const char *cpaMarkName[5];
extern const char *cpaPartsLocName[1];

#endif // KART2DCOMMON_H
