#ifndef KART2DCOMMON_H
#define KART2DCOMMON_H

#include <JSystem/J2D/J2DPane.h>

class Kart2DCommon
{ // Autogenerated
public:
    void changeNumberTexture(int, J2DPicture **, u8, bool, bool); // 0x8020edd0
    void getAsciiTexture(char);                                   // 0x8020ef24
    void changeStringTexture(const char *, J2DPicture **, u8);    // 0x8020effc
    Kart2DCommon();                                               // 0x8020f158
    virtual ~Kart2DCommon() { mspKart2DCommon = nullptr; }        // 0x8020f48c

    static void create(JKRHeap *heap)
    {
        if(mspKart2DCommon == nullptr)
            mspKart2DCommon = new (heap, 0) Kart2DCommon();
    }

private:
    static Kart2DCommon *mspKart2DCommon; // 0x80416a70
    void *mNumberFont[11];                // 0 to 9, including colon?
    void *mFontData[46];                  // chars A to Z + some other data
    void *mIndexKartImg[21];
    void *mPartName[4];
    void *mPartsLocName;
    void *mPosImg[8];
    void *mResCupImg[5];
    void *mCupImg[5];
    void *BattleIconImg[3];
    void *mMark[5];
    void *mAlphaTex;
}; // Size:0x1bc

extern char *cpaCharName[20];
extern char *cpaKartName[21];
extern char *cpaPartsName[4];
extern char *cpaCupName[5];
extern char *cpaCupIcon[5];
extern char *cpaBattleIcon[3];
extern char *cpaMarkName[3];
extern char *cpaPartsLocName;

#endif // KART2DCOMMON_H