#ifndef LANENTRY_H
#define LANENTRY_H

#include <JSystem/J2D/J2DPane.h>
#include <JSystem/JKernel/JKRArchive.h>

class LANEntry { // Autogenerated
public:
    LANEntry(JKRArchive *, JKRArchive *); // 0x80216cd0
    void waitEntry(); // 0x80217190
    void endReceipt(); // 0x80217660
    void setRaceInfo(); // 0x802176b4
    void calc(); // 0x80217bb0
    void calcAnm(); // 0x80217cb0
    void draw(const J2DGrafContext *); // 0x8021821c
    void start(); // 0x8021826c
    void entry(); // 0x8021843c
    void unentry(); // 0x80218450
    void startTimer(); // 0x8021845c
    void stopTimer(); // 0x80218468
    // Inline/Unused
    void changeNumberTexture(int);
    void receiptEntry(int);
    void cancelEntry(int);
}; // class LANEntry
#endif // LANENTRY_H
