#ifndef LANTITLE_H
#define LANTITLE_H

#include <JSystem/J2D/J2DPane.h>
#include <JSystem/JKernel/JKRArchive.h>

class LANTitle { // Autogenerated
public:
    class Item {
    public:
        void calc(); // 0x80216534
        // Inline/Unused
        Item(int, J2DScreen *, void *, void *);
    };

    LANTitle(JKRArchive *); // 0x80216640
    void calc(); // 0x8021682c
    void calcAnm(); // 0x80216a6c
    void draw(const J2DGrafContext *); // 0x80216b14
    void start(); // 0x80216b40
    // Inline/Unused
    void selectIn();
    void selectOut();
    void unselect();
}; // class LANTitle
#endif // LANTITLE_H
