#ifndef LOGOAPP_H
#define LOGOAPP_H

#include "Osako/Clock.h"
#include "Osako/GameApp.h"
#include "Osako/PrintApp.h"

class LogoApp : public GameApp
{ // Autogenerated
public:
    enum OpeningState // TODO: check properly with dolphin to really see what eavh state does
    {
        mcInitSystem,
#ifndef REGION_EU
        mcStartSystem,
#else
        mcStartSystem = mcInitSystem,
#endif
        mcLogoInitMemoryCard,
        mcLogoCheckFrameTime,
        mclogoStartAudio,
        mcLogoFadeIn,
        mcLogoFadeOut,
        mcDolbyFadeIn,
        mcDialogFadeIn,
        mcDialogPickOption,
        mcDialogApplyOption,
        mcRenderModeChangeFadeIn,
        mcDialogFadeOut,
        mcLoadOpening
    };

    static LogoApp *create();              // 0x801fe074
    static void call();                    // 0x801fe0c4
    LogoApp();                             // 0x801fe0e8
    virtual ~LogoApp();                    // 0x801fe190
    virtual void draw();                   // 0x801fe1f0
    virtual void calc();                   // 0x801fe238
    virtual void reset();                  // 0x801fe84c
    static void createMoviePlayer(void *); // 0x801fe820
    void restart();                        // 0x801fe850
    void controlLoading();                 // 0x801fe8d0

    f32 getFrameTime()
    {
        switch (_28)
        {
        case 1:
            return Clock::calcFrameTime(_1c);
            break;
        case 2:
            return _24;
            break;
        default:
            return 0.0f;
            break;
        }
    }

private:
    static LogoApp *mspLogoApp; // 0x80416960
    PRINTAPP_TYPE *mPrintApp;   // 0xc
    int mShowDialog;            // 0x10
    OpeningState mState;        // 0x14
    int mFadeTimer;             // 0x18
    u32 _1c;
    u32 _20;
    f32 _24;
    u8 _28;
    f32 _2c;
    f32 _30;
    int _34;
    bool mIsLoadingMovie;
}; // class LogoApp

#endif // LOGOAPP_H