#ifndef LOGOAPP_H
#define LOGOAPP_H

#include "Osako/GameApp.h"

class LogoApp : public GameApp
{ // Autogenerated
    // Global
public:
    static LogoApp *create();              // 0x801fe074
    static void call();                    // 0x801fe0c4
    LogoApp();                             // 0x801fe0e8
    virtual ~LogoApp();                    // 0x801fe190
    virtual void draw();                   // 0x801fe1f0
    virtual void calc();                   // 0x801fe238
    virtual void reset();                  // 0x801fe84c
    static void createMoviePlayer(void *); // 0x801fe820
    void restart();                        // 0x801fe850
    void controlLoading();                 // 0x801fe8d0
    static LogoApp *mspLogoApp;            // 0x80416960
}; // class LogoApp
#endif // LOGOAPP_H