#ifndef MENUBACKGROUND_H
#define MENUBACKGROUND_H

#include "JSystem/J2D/J2DScreen.h"
#include "JSystem/JKernel/JKRArchive.h"

class MenuBackground
{ // Autogenerated
public:
    MenuBackground(JKRArchive *); // 0x8021906c
    void calc();                  // 0x802190f0

    ~MenuBackground() { mspMenuBackground = nullptr; }

    static MenuBackground *ptr() { return mspMenuBackground; }

private:
    static MenuBackground *mspMenuBackground; // 0x80416a88

    J2DScreen mScreen; // 00 - 118 J2DScreen
    J2DAnmTextureSRTKey *mAnimation;
    s16 mAnimFrame;
}; // Size: 0x120

#endif // MENUBACKGROUND_H
