#ifndef NETGATEAPP_H
#define NETGATEAPP_H

#include <JSystem/JKernel/JKRArchive.h>

#include "Osako/GameApp.h"



class NetGateApp : public GameApp
{ // Autogenerated
public:
    static NetGateApp *create(); // 0x80209424
    static void call(bool);      // 0x80209474
    NetGateApp();                // 0x8020949c
    virtual ~NetGateApp();       // 0x8020950c, overide
    void loadTask(void *arg);    // 0x80209594
    virtual void draw();         // 0x802096e4, overide
    virtual void calc();         // 0x80209768, overide
    virtual void reset();        // 0x80209b8c, overide

    // Inline/Unused
    // void modeSelect();
    // void titleMenu();
    // void waitEntry();

    // Inline
    static NetGateApp *ptr() { return mspNetGateApp; }

    bool hasActiveTask() { return mHasActiveTask; }

private:
    static NetGateApp *mspNetGateApp; // 0x80416a20
    static bool msSkip;               // 0x80416a24
    
    u8 _0c[0x14 - 0xc];
    JKRArchive *mpSceneArc;
    JKRArchive *_18;
    JKRArchive *_1c;
    u8 _20[0x30 - 0x20];
    bool mHasActiveTask;

}; // Size: 0x34
#endif // NETGATEAPP_H
