#ifndef RESETAGENT_H
#define RESETAGENT_H

#include "JSystem/JUtility/JUTGamePad.h"

namespace ResetAgent
{ // Autogenerated
    // Global
    extern void callbackReset(int, void *); // 0x8020f4dc
    void reset(bool);                       // 0x8020f508
    void draw();                            // 0x8020f530
    void calc();                            // 0x8020f534
    // void msState;                    // 0x80416a78
    // void msCount;                    // 0x80416a7c
    // void msForceMenu;                // 0x80416a80
    // void msInvalid;                  // 0x80416a81
    // void msAudioReset;               // 0x80416a82
};     // namespace ResetAgent
#endif // RESETAGENT_H