#ifndef TESTVIEWAPP_H
#define TESTVIEWAPP_H

#include "Osako/GameApp.h"

class TestViewApp : public GameApp
{ // Autogenerated
public:
    static TestViewApp *create(); // 0x80209c9c
    static bool call();           // 0x80209cec
    TestViewApp();                // 0x80209d10
    virtual ~TestViewApp();       // 0x80209d70, overide
    virtual void reset();         // 0x80209dd0, overide
    virtual void draw();          // 0x80209df4, overide
    virtual void calc();          // 0x80209fb4, overide

    static TestViewApp *ptr() { return mspTestViewApp; }

private:
    static TestViewApp *mspTestViewApp; // 0x80416a28

    int mMenuIndex;
    BOOL mJ2DInitialized;  // 10
    int mMenuOption;       // 14
    int mDvdError;         // 18
    int mPrintOption;      // 1c
    int mMemoryCardOption; // 20

};     // 24;
#endif // TESTVIEWAPP_H