#ifndef MOVIEAPP_H
#define MOVIEAPP_H

#include "Osako/GameApp.h"
#include "Shiraiwa/JugemMain.h"

class TJugemVoidRod;
class TJugemHeadHear;

class MVActor
{
public:
    MVActor();
    ~MVActor() {}
    virtual void setCurViewNo(u32) = 0;
    virtual void calc() = 0;
    virtual void update() = 0;
    virtual void viewCalc(u32) = 0;

    JSULink<MVActor> mLink;
};

class MovieJugemActor : public MVActor
{
public:
    MovieJugemActor();

    static void loadModelData(GeographyObj *);
    virtual void setCurViewNo(u32);
    virtual void calc();
    virtual void update();
    virtual void viewCalc(u32);
    void endDemo();
    bool isDemoEnd();
private:
    TJugem *mJugem;
    TJugemVoidRod *mVoidRod;
    TJugemRodItem* mRodItem;
    TJugemHeadHear *mHear;
    int mCalcCnt;

}; // Size: 0x28

class MovieApp : public GameApp
{ // Autogenerated
public:
    static void getArchive(const char *); // 0x801d799c
    static MovieApp *create();            // 0x801d79c4
    static void call();                   // 0x801d7a98
    MovieApp(void *);                     // 0x801d7abc
    void isEnd();                         // 0x801d7d9c
    void loadOpeningData();               // 0x801d7e64
    void doRunning();                     // 0x801d7e88
    void doEnding();                      // 0x801d8004

    // Vtable
    virtual ~MovieApp();  // 08
    virtual void draw();  // 0C
    virtual void calc();  // 10
    virtual void reset(); // 14

    static MovieApp *getMovieApp() { return sMovieApp; }

private:
    static MovieApp *sMovieApp; // 0x80416840
    static void *mspHeapBuffer; // 0x80416844

private:
    MovieJugemActor *mActor;
}; // Size: 0x2c

#define MOVIE_GetHeap() \
    MovieApp::getMovieApp()->getHeap()

#define MOVIE_loadOpeningData() \
    MovieApp::getMovieApp()->loadOpeningData()

#endif // MOVIEAPP_H