#ifndef KARTPIPE_H
#define KARTPIPE_H

#include "Kaneshige/JugemPoint.h"

#include "types.h"

class KartBody;

class KartPipe
{ // Autogenerated
public:
    KartPipe() {}

    void Init(int);        // 0x8031228c
    void MakePipe();       // 0x803122d4
    void DoKeep();         // 0x80312494
    void DoCatch();        // 0x8031250c
    void SetPose();        // 0x8031256c
    void DoShoot();        // 0x803127e0
    void DoCheckOutView(); // 0x80312850
    void DoCheckEnd();     // 0x80312914
    void DoPipeCrl();      // 0x803129a4
    void DoAfterPipeCrl(); // 0x80312b8c
private:
    JugemPoint *mPoint; // 00
    KartBody *mBody;    // 04
    u8 mFlags;          // 08
    u8 mState;          // 09
    u8 mTimer;          // 0a
    u16 _c;             //
    int mCameraID;      // 10
    u8 _14[4];          //
    f32 mSpeed;         // 18
    u8 _1c[4];          //
    JGeometry::TVec3f _20; //
    JGeometry::TVec3f _2c; //
    JGeometry::TVec3f _38; //
}; // 44

#endif // KARTPIPE_H