#ifndef KARTTIRE_H
#define KARTTIRE_H

class KartBody;

class KartTire
{ // Autogenerated
public:
    KartTire() {}

    void Init(int idx); // 0x80307eb8
    // Inline/Unused
    // void MakeComeOff();
    // void DoComeOffCrl();
private:
    KartBody *mBody;
    u8 _4;
    u8 _5;
    u8 _6;
    u16 _8;
};
#endif // KARTTIRE_H