#ifndef KARTANT_H
#define KARTANT_H

#include <JSystem/JGeometry/Vec.h>

#include "Shiraiwa/MapObjAntLion.h"

#include "types.h"

class KartBody;

class KartAnt
{ // Autogenerated
public:
    KartAnt() {}

    void Init(int);       // 0x80312ca8
    void DoKeep();        // 0x80312cf0
    void DoCatch();       // 0x80312d68
    void SetPose();       // 0x80312da8
    void DoShoot();       // 0x80312fac
    void DoCheckEnd();    // 0x80313044
    void DoAntCrl();      // 0x8031310c
    void DoAfterAntCrl(); // 0x803131fc
    // Inline/Unused
    // void MakeAnt(GeographyObj *);
private:
    u8 _0;
    KartBody *mBody;
    TMapObjAntLion *mAntLion;
    u8 mFlags;
    u8 mState;
    u8 mTimer;
    u8 _f[0x20 - 0xf];
    JGeometry::TVec3f _20;
    JGeometry::TVec3f _2c;
    JGeometry::TVec3f _38;
};
#endif // KARTANT_H