#ifndef KARTSTAR_H
#define KARTSTAR_H

#include "types.h"

class KartBody;

class KartStar
{ // Autogenerated
public:
    KartStar() {}

    void Init(int idx); // 0x80307c44
    void MakeStar();    // 0x80307c90
    void StopStar();    // 0x80307d28
    void DoStarCrl();   // 0x80307d94
private:
    KartBody *mBody;
    u8 _04;
    u8 _05;
    u16 mTimer;
}; // Size: 0x8

#endif // KARTSTAR_H