#ifndef KARTHANDLE_H
#define KARTHANDLE_H

#include "Kameda/MotorManager.h"

#include "types.h"

class KartHandle
{ // Autogenerated
public:
    KartHandle() {}

    void Init(int);                                         // 0x80311ae8
    void DoMotor(MotorManager::MotorType);                  // 0x80311b34
    void DoPowerMotor(float, unsigned char, unsigned char); // 0x80311cac
    void StopMotor();                                       // 0x80311df8
    void WatchFrontalCollisionForce();                      // 0x80311e64
private:
    // TODO
};
#endif // KARTHANDLE_H