#ifndef KARTDOSSIN_H
#define KARTDOSSIN_H

#include "Sato/GeographyObj.h"
#include "types.h"

class KartBody;

class KartDossin
{ // Autogenerated
public:
    KartDossin() {}

    void Init(int);                  // 0x80303f70
    void DoDossinTimer();            // 0x80303fd8
    void MakeDossin(GeographyObj *); // 0x80303ff0
    bool DoDossin();                 // 0x803041c4
    void DoKeep();                   // 0x80304410
    void DoClear();                  // 0x803044d4
    void DoCheck();                  // 0x80304548
    bool DoReturn();                 // 0x803045a4
    bool DoShake();                  // 0x80304610
    bool DoCheckEnd();               // 0x80304694
    void DoDossinCrl();              // 0x803046f8
    void DoAfterDossinCrl();         // 0x803048b8

    KartBody *mBody;
    GeographyObj *mGeoObj;
    JGeometry::TVec3f mVelocity;
    u8 _14;
    u8 _15;
    u16 _16;
    u16 mKartFlattenedTimer;         // _18
    f32 _1c;
    f32 _20;
    f32 _24;
    f32 _28;
}; // 2c

#endif // KARTDOSSIN_H
