#ifndef KARTTIRE_H
#define KARTTIRE_H

class KartTire
{ // Autogenerated
public:
    KartTire() {}

    void Init(int); // 0x80307eb8
    // Inline/Unused
    // void MakeComeOff();
    // void DoComeOffCrl();
private:
    // TODO
};
#endif // KARTTIRE_H