#ifndef KARTSTAR_H
#define KARTSTAR_H

class KartStar
{ // Autogenerated
public:
    KartStar() {}

    void Init(int);   // 0x80307c44
    void MakeStar();  // 0x80307c90
    void StopStar();  // 0x80307d28
    void DoStarCrl(); // 0x80307d94
private:
    // TODO
};
#endif // KARTSTAR_H