#ifndef KARTANT_H
#define KARTANT_H

class KartAnt
{ // Autogenerated
public:
    KartAnt() {}

    void Init(int);       // 0x80312ca8
    void DoKeep();        // 0x80312cf0
    void DoCatch();       // 0x80312d68
    void SetPose();       // 0x80312da8
    void DoShoot();       // 0x80312fac
    void DoCheckEnd();    // 0x80313044
    void DoAntCrl();      // 0x8031310c
    void DoAfterAntCrl(); // 0x803131fc
    // Inline/Unused
    // void MakeAnt(GeographyObj *);
private:
    // TODO
};
#endif // KARTANT_H