#ifndef KARTDEMOCAM_H
#define KARTDEMOCAM_H

#include "Kaneshige/Course/CrsData.h"

#include "Yamamoto/kartCtrl.h"

class KartCam;

class KartDemoCam
{ // Autogenerated
public:
    KartDemoCam() {}

    void Init(KartCam *);                       // 0x8030a1e8
    void ChaseFovy(const CrsData::Camera *);    // 0x8030a24c
    void DoInitCol();                           // 0x8030a338
    void DoCol();                               // 0x8030a380
    void InitFixCam();                          // 0x8030a4bc
    void DoFixCam();                            // 0x8030a61c
    void InitFixSearchCam();                    // 0x8030a6b8
    void DoFixSearchCam();                      // 0x8030a794
    void InitFixChaseCam();                     // 0x8030a8b0
    void DoFixChaseCam();                       // 0x8030aa60
    void InitChaseCam();                        // 0x8030abd8
    void DoChaseCam();                          // 0x8030ad20
    void InitFixPathCam();                      // 0x8030ae98
    void DoFixPathCam();                        // 0x8030affc
    void InitChasePathCam();                    // 0x8030b1d8
    void DoChasePathCam();                      // 0x8030b2fc
    void InitFixSplCam();                       // 0x8030b508
    void DoFixSplCam();                         // 0x8030b6c4
    void InitChaseSplCam();                     // 0x8030b894
    void DoChaseSplCam();                       // 0x8030ba24
    void InitFixPalaCam();                      // 0x8030bc28
    void DoFixPalaCam();                        // 0x8030bff4
    void InitDemoPathCam();                     // 0x8030c31c
    void DoDemoPathCam();                       // 0x8030c414
    void InitDemoParallelView();                // 0x8030c5b8
    void DemoParallelView();                    // 0x8030c6a8
    void InitDemoGoalView();                    // 0x8030c798
    void DemoGoalView();                        // 0x8030cb4c
    void MapView();                             // 0x8030cec4
    void ObjectView();                          // 0x8030d36c
    void DemoInitID();                          // 0x8030d650
    void InitID();                              // 0x8030d7b8
    void DoDemoView();                          // 0x8030d93c
    void LiveViewChange();                      // 0x8030da9c
    void DemoView();                            // 0x8030db6c
    void DoPathEnd(JGeometry::TVec3f *, f32 *); // 0x8030dd34
    void InitStartFixPathCam();                 // 0x8030de9c
    void DoStartFixPathCam();                   // 0x8030df74
    void InitStartPathCam();                    // 0x8030e07c
    void DoStartPathCam();                      // 0x8030e15c
    void InitStartLookPathCam();                // 0x8030e2bc
    void DoStartLookPathCam();                  // 0x8030e364
    void InitStartOnlyPathCam();                // 0x8030e450
    void DoStartOnlyPathCam();                  // 0x8030e574
    void InitStartFixCam();                     // 0x8030e6d0
    void DoStartFixCam();                       // 0x8030e7f8
    void InitStartChasePathCam();               // 0x8030e8c0
    void DoStartChasePathCam();                 // 0x8030e9c4
    void InitVsLastCam();                       // 0x8030ebc0
    void VsLastCam();                           // 0x8030ecb0
    void InitLastCam();                         // 0x8030eeb4
    void LastCam();                             // 0x8030f160
    void InitStartDemoCam();                    // 0x8030f5c4
    void StartDemoCam();                        // 0x8030f6ac
    void SetLastDemo();                         // 0x8030f7a0
    void SetRaceCam();                          // 0x8030f7fc
    void SetNextID();                           // 0x8030f85c
    void DoExecution();                         // 0x8030f8ec
    u8 GetStartID();                          // 0x8030f94c
    void InitStartID(bool);                     // 0x8030f9b0
    void StartDemoView();                       // 0x8030f9e8
    void InitStartMapCam();                     // 0x8030fa08
    void StartMapCam();                         // 0x8030faf0
    void SetMapNextID();                        // 0x8030fbcc
    void SetUpMapID();                          // 0x8030fc40
    void InitStaffView();                        // 0x8030fc9c
    void StaffView();                           // 0x8030fdbc
    void SetStaffNextID();                      // 0x8030ff40
    void SetUpStaffID();                        // 0x8030ffb8
    // Inline/Unused
    // void GetPerView();
    // void KartBody::getPerCam();

    KartCam *mCam;
    KartBody *mBody;
    Mtx mPosMtx;
    u16 _38;
    u8 _3a[0x70 - 0x3a];
    f32 mCamKartDiffLength;
    JGeometry::TVec3f _74;
    JGeometry::TVec3f _80;
    JGeometry::TVec3f _8c;
    JGeometry::TVec3f mCamKartDiff;
    JGeometry::TVec3f _a4;
    u8 _b0[0x110 - 0xb0];
}; // 110

#endif // KARTDEMOCAM_H