#ifndef KARTRESCUE_H
#define KARTRESCUE_H

#include "Sato/GeographyObj.h"

class KartBody;

class KartRescue
{ // Autogenerated
public:
    KartRescue() {}

    void Init(int);                      // 0x80300878
    void DoKeep();                       // 0x80300910
    void GetJugemuStatus();              // 0x803009a8
    void SetPose(u8);                    // 0x80300aec
    void SetJugemuPose(int, KartBody *); // 0x80300eb4
    void DoMove(KartBody *);             // 0x80300f7c
    void SetHookPos(KartBody *);         // 0x803010a8
    void DoCatch();                      // 0x803010f8
    void DoTop();                        // 0x803011c0
    void DoDrop();                       // 0x80301340
    void DoCheckEnd();                   // 0x8030144c
    void MakeRescue(GeographyObj *, u8); // 0x80301674
    void DoRescueCrl();                  // 0x80301968
    void DoAfterRescueCrl();             // 0x8030249c

    // Inline/Unused
    // void DoHang();
private:
    // TODO
};
#endif // KARTRESCUE_H