#ifndef KARTRESCUE_H
#define KARTRESCUE_H

#include <JSystem/JGeometry/Vec.h>

#include "Sato/GeographyObj.h"

#include "types.h"

class KartBody;

class KartRescue
{ // Autogenerated
public:
    KartRescue() {}

    void Init(int);                      // 0x80300878
    void DoKeep();                       // 0x80300910
    void GetJugemuStatus();              // 0x803009a8
    void SetPose(u8);                    // 0x80300aec
    void SetJugemuPose(int, KartBody *); // 0x80300eb4
    void DoMove(KartBody *);             // 0x80300f7c
    void SetHookPos(KartBody *);         // 0x803010a8
    void DoCatch();                      // 0x803010f8
    void DoTop();                        // 0x803011c0
    void DoDrop();                       // 0x80301340
    void DoCheckEnd();                   // 0x8030144c
    void MakeRescue(GeographyObj *, u8); // 0x80301674
    void DoRescueCrl();                  // 0x80301968
    void DoAfterRescueCrl();             // 0x8030249c

    // Inline/Unused
    // void DoHang();
private:
    u8 _0[0xc];            //
    CrsGround mGround;     // c
    u8 _6c[0x8c - 0x6c];   //
    JGeometry::TVec3f _8c; //
    JGeometry::TVec3f _98; //
    JGeometry::TVec3f _a4; //
    JGeometry::TVec3f _b0; //
    JGeometry::TVec3f _bc; //
    JGeometry::TVec3f _c8; //
    u8 _d4[0x104 - 0xd4];  //

}; // 0x104

#endif // KARTRESCUE_H