#ifndef KARTPERCAM_H
#define KARTPERCAM_H

class KartPerCam
{ // Autogenerated
public:
    KartPerCam() {}

    void Init(int);              // 0x80315160
    void InitFixCam();           // 0x803151d4
    void InitFixSearchCam();     // 0x803152d0
    void InitFixChaseCam();      // 0x80315364
    void InitChaseCam();         // 0x803154b4
    void InitFixPathCam();       // 0x803155a8
    void InitChasePathCam();     // 0x803156b0
    void InitFixSplCam();        // 0x80315780
    void InitChaseSplCam();      // 0x803158d8
    void InitFixPalaCam();       // 0x80315a00
    void InitDemoPathCam();      // 0x80315cfc
    void InitDemoParallelView(); // 0x80315dbc
    void InitID();               // 0x80315e3c
    // Inline/Unused
    // void ChaseFovy();
    // void DoFixCam();
    // void DoFixSearchCam();
    // void DoFixChaseCam();
    // void DoChaseCam();
    // void DoFixPathCam();
    // void DoChasePathCam();
    // void DoFixSplCam();
    // void DoChaseSplCam();
    // void DoFixPalaCam();
    // void DoDemoPathCam();
    // void DemoParallelView();
    // void InitDemoGoalView();
    // void DemoGoalView();
    // void DemoView();
private:
    // TODO
};
#endif // KARTPERCAM_H