#ifndef KARTSTRAT_H
#define KARTSTRAT_H

#include <JSystem/JGeometry.h>

#include "Kameda/MotorManager.h"

class KartBody;

class KartStrat
{ // Autogenerated
public:
    KartStrat() {}
    void Init(int);
    void GetBodySpeed();
    void GetBodyRoll();
    void GetRoadBodyRoll();
    void GetBodyNorm();
    void DoEnemyMaxmZCrl(f32);
    void DoMaxLevelZXVelCrl(f32, f32);
    void DoVelCrl(f32);
    void DoWgCrl(f32);
    void DoRotPose(JGeometry::TVec3f, f32);
    void DoPoseCrl();
    void MovingSpinClear();
    void MovingHalfSpinClear();
    void MovingTornadeClear();
    void FreezeClear();
    void RollCrashClear();
    void AllGravyClear();
    void GravyClear();
    void LiftClear();
    void PitchClear();
    void DashClear();
    void OtherClear();
    void ShakeGround();
    void DoAdjustment();
    void DoWheelSpinCrl();
    void DoWallCrl();
    void DoYawLimit();
    void DoRollLimit();
    void DoLiftCrl();
    void DoLiftYawCrl();
    void DoRollLim(f32, f32);
    void DoPitchLim();
    void DoRollCrash();
    void DoTestPitchCrl();
    void DoDashCrl(f32);
    void DoStarCrl(f32);
    void DoAirCrl();
    void DoYawCrl();
    void DoSignalCrl();
    void DoSpeedCrl();
    void DoComSpeedCrl();
    void DoCutSlide();
    void DoCalcSpeed();
    void DoMotor(MotorManager::MotorType);
    void DoPowerMotor(f32, u8, u8);
    void DashSpeedCtrl(f32);
    void DashSpSpeedCtrl(f32);
    void CompulsionDash(JGeometry::TVec3f *);
    void DoDash();
    int DoStatusCrl();
    // KartCtrlInfo
    void DoStepAccel();
    void DoStepSterr();
    void DoSterr();
    void DoAccel();

    // Inline/Unused
    // void DoMaxmZCrl(f32);
    // void DoMaxVelCrl(f32);
    // void DoMaxZXVelCrl(f32);
    // void DoZXVelCrl(f32);
    // void DoMaxLevelZXDirCrl(f32, f32);
    // void KameCrashClear();
    // void BombCrashClear();
    // void AllParamClear();
    // void JumpClear();
    // void DoJumpCrl();
private:
    KartBody *mBody;

}; // 0x4

#endif // KARTSTRAT_H
