#ifndef JAUDIO_JASCMDSTACK_H
#define JAUDIO_JASCMDSTACK_H

#include "JSystem/JSupport/JSUList.h"

struct JASPortArgs; // TODO

class JASPortCmd { // Autogenerated
public:
    class TPortHead {
    public:
        void execCommandOnce();
        void execCommandStay();
    private:
        JSUList<JASPortCmd> mList;
    };
    static void addPortCmdOnce();
    void addPortCmdStay();
    void cancelPortCmdStay();
    void setPortCmd(void (*func)(JASPortArgs *), JASPortArgs *args);
    static void execAllCommand();

    static TPortHead sCommandListOnce;
    static TPortHead sCommandListStay;
}; // class JASCmdStack

#endif // JAUDIO_JASCMDSTACK_H
