#ifndef JASPROBE_H
#define JASPROBE_H

#include "types.h"

class JASProbe { // Autogenerated
public:
    static void start(s32, const char *); // 0x80090c48
    static void stop(s32); // 0x80090cb4
    static JASProbe* sProbeTable[16]; // 0x803faa9c
    // Inline/Unused
    JASProbe();
    void reset();
    void start(const char *);
    void stop();
    void registProbe(s32, JASProbe *);
    static const char *sDefaultName;

    char const* mName;
	s32 mStartTime;
	f32 _08;
	f32 _0C;
	f32 _10;
	f32 _14;
	f32 _18[100]; 
	u32 _1A8;
}; // class JASProbe

#endif // JASPROBE_H
