#ifndef DEMO2D_H
#define DEMO2D_H

#include "Kaneshige/HioMgr.h"

class Demo2D
{ // Autogenerated
public:
    Demo2D(JKRHeap *); // 0x8018313c
    void init();       // 0x8018325c
    void draw();       // 0x801832d0
    void calc();       // 0x80183344

    class Demo2DParam : public JORReflexible
    {
        // Inline/Unused
        Demo2DParam();
        virtual ~Demo2DParam() {}
    };

    class Demo2DHioNode 
    {
    };

    // Inline/Unused
    ~Demo2D();
};     // class Demo2D
#endif // DEMO2D_H
