#ifndef _FADE_H
#define _FADE_H

#include <JSystem/JKernel/JKRHeap.h>
#include <JSystem/JUtility/TColor.h>

#include "types.h"

// Considering this is similar to Mario.h, the might be some sort of inheritance going on?

class Fade
{ // Autogenerated
public:
    Fade(JKRHeap *);                       // 0x8013b318
    void init();                           // 0x8013b76c
    void draw(int, f32, JUtility::TColor); // 0x8013b770
    // Inline/Unused
    ~Fade();

private:
    u8 _0[0x34];
}; // class Fade

#endif