#ifndef _MARIO_H
#define _MARIO_H

#include <JSystem/JKernel/JKRHeap.h>
#include <JSystem/JUtility/TColor.h>

#include "types.h"

class Mario
{ // Autogenerated
public:
    Mario(JKRHeap *heap);                   // 0x8016eed0
    void init();                            // 0x8016f4cc
    void draw(f32, JUtility::TColor color); // 0x8016f4d0
    // Inline/Unused
    ~Mario();
    void draw(int, f32, JUtility::TColor color);

private:
    u8 _0[0x30];
}; // class Mario

#endif