#ifndef MOTORMANAGER_H
#define MOTORMANAGER_H

#include "JSystem/JKernel/JKRDisposer.h"

#include "types.h"

class MotorManager : JKRDisposer
{ // Autogenerated
public:
    // Global
    enum MotorType
    {
        MotorType_0,
        MotorType_1,
        MotorType_2,
        MotorType_3,
        MotorType_4,
        MotorType_5,
        MotorType_6,
        MotorType_7,
        MotorType_8,
        MotorType_9,
        MotorType_10,
        MotorType_11,
        MotorType_12,
        MotorType_13,
        MotorType_14,
        MotorType_15,
        MotorType_16,
        MotorType_17,
        MotorType_18,
        MotorType_19,
        MotorType_20,
        MotorType_21,
        MotorType_22
    };

    MotorManager(JKRHeap *);                // 0x80130e58
    virtual ~MotorManager();                // 0x80130ee0
    void reset();                           // 0x80130f48
    void exec();                            // 0x80130fc0
    void setMotor(MotorType, int);          // 0x8013103c
    void setAwardMotor(MotorType);          // 0x80131218
    void setPowerMotor(int, float, u8, u8); // 0x801312e8

    static MotorManager *getManager() { return mThis; };

    static int mCountFrame;     // 0x803fb640
    static MotorManager *mThis; // 0x80416280

private:
    u8 _0[8];
};

#endif