#ifndef READPRINTMESSAGE_H
#define READPRINTMESSAGE_H

#include <JSystem/J2D/J2DPane.h>

#include "Kameda/PrintDvdError.h"
#include "Kameda/PrintProgressive.h"
#include "Kameda/PrintMemoryCard.h"
#include "Kawano/PrintPal.h"

namespace ReadPrintMessage
{ // Autogenerated
    // Global
    u32 getColor(void *bmcPtr, int index);                            // 0x801690b4
    u8 getDefaultColor(void *bmgPtr);                                 // 0x80169330
    u16 getRate(void *, int);                                        // 0x801694ec
    s8 getCharSpace(void *, int);                                    // 0x801696b4
    char *getMessage(void *, int);                                   // 0x8016987c
    void tagCnv(char *, void *, J2DTextBox::TFontSize, int, char *); // 0x80169a50
    int getBmgMessageID(PrintDvdError::MessageID);                   // 0x8016a600
    int getBmgMessageID(PrintProgressive::MessageID);                // 0x8016a6f8
    int getBmgMessageID(PrintPal::MessageID);                        // 0x801520b8(PAL)
    int getBmgMessageID(PrintMemoryCard::MessageID);                 // 0x8016a7a8    
    int getBmgMessageID(int);                                        // 0x8016aa10

    extern int mNum;       // 0x803fbf34
    extern char *mStr;     // 0x803fbf70
    extern void *mInfoPtr; // 0x80416350
    extern void *mDataPtr; // 0x80416354
    // Inline/Unused
    // void readBmg(void *);

}; // namespace ReadPrintMessage

#endif // READPRINTMESSAGE_H
