#ifndef SCENEAPP_H
#define SCENEAPP_H

#include "Osako/GameApp.h"

class SceneApp : public GameApp
{ // Autogenerated
public:
    static SceneApp *create(); // 0x8013c2b8
    static void call();        // 0x8013c308
    SceneApp();                // 0x8013c32c
    virtual ~SceneApp();       // 0x8013c384, overide
    virtual void draw();       // 0x8013c3e4, overide
    virtual void calc();       // 0x8013c4b4, overide

    static SceneApp *ptr() { return mspSceneApp; }

private:
    static SceneApp *mspSceneApp; // 0x804162d8
};

#endif // SCENEAPP_H
