#ifndef SCENECOURSESELECT_H
#define SCENECOURSESELECT_H

#include "types.h"
#include "kartEnums.h"

#include <JSystem/JKernel/JKRArchive.h>

class SceneCourseSelect { // Autogenerated
public:
    struct CourseData {
        ECourseID courseID;
        const char *coName;
        const char *copName;
    };

    SceneCourseSelect(JKRArchive *, JKRHeap *); // 0x80186db0
    void reset(); // 0x80187784
    void init(); // 0x80187b18
    ~SceneCourseSelect(); // 0x80187dac
    void draw(); // 0x80187e48
    void calc(); // 0x80187f74
    void course_init(); // 0x801886b0
    void course(); // 0x80188874
    void buttonA(); // 0x80188ce8
    void buttonB(); // 0x80188ef4
    void course_end(); // 0x80188f78
    void nextScene(); // 0x801890f0
    void nextRace(); // 0x801891b4
    void calcAnm(); // 0x80189448
    void setTexture(); // 0x80189bf4
    void setRivalKart(); // 0x8018a22c
    void setStartNo(); // 0x8018a580
    void rndRoulette(); // 0x8018a71c

    static ERaceGpCup mRaceGpCup[5]; // 0x80375368
    static CourseData mCourseData[]; // 0x80375788
    static u64 mCourseSelectBckTag[42]; // 0x80375878
    static u64 mCourseSelectBtkTag[4]; // 0x803759c8
    static u64 mCourseSelectBpkTag[2]; // 0x803759e8
    static const char *mCupName[5]; // 0x803957d0
    static const char *mSelectCupName[5]; // 0x803957e4
    static int mCup; // 0x80416368
    static int mCourse; // 0x8041636c
}; // class SceneCourseSelect
#endif // SCENECOURSESELECT_H
