#ifndef LIGHTMGR_H
#define LIGHTMGR_H

#include "JSystem/JGeometry.h"
#include "dolphin/gx.h"
#include "types.h"

// TODO: everything
class LightObj {
public:
    LightObj(const char *);
    virtual ~LightObj();
    void init(const char *, u32);
    void setTagName(u32);
};

class LtObjAmbient : public LightObj {
public:
    LtObjAmbient(const char *, JUtility::TColor);
    virtual ~LtObjAmbient();
    void getColor(JUtility::TColor *) const;
    void draw();
};

class LtObjDiffuse : public LightObj {
public:
    virtual ~LtObjDiffuse();
    void setGXObj();
    void draw();
    void load(_GXLightID);
    
};

class LightMgr
{ // Autogenerated
public:
    // Global
    LightMgr();                      // 0x801b3ec0
    void createCharColor();          // 0x801b3fb8
    static int createManager();      // 0x801b3fbc
    void appendLight(LightObj *);    // 0x801b400c
    void removeLight(LightObj *);    // 0x801b4054
    void draw();                     // 0x801b409c
    void calc();                     // 0x801b4278
    void searchLight(unsigned long); // 0x801b431c
    ~LightMgr();                     // 0x801b446c

    static LightMgr *getManager() {return sLightManager; };

    static LightMgr * sLightManager;          // 0x804163b8
    // Inline/Unused
    // void reset();
    // void searchRaceSceneLight(unsigned long);
    // void searchRaceKartLight(unsigned long, int);
}; // class LightMgr

// void RaceSceneLight::getTagName(unsigned long);

#endif