#ifndef MDLVIEWER_H
#define MDLVIEWER_H

#include <JSystem/JSupport.h>

class MVActor
{
public:
    MVActor();
    ~MVActor() {}
    virtual void setCurViewNo(u32) = 0;
    virtual void calc() = 0;
    virtual void update() = 0;
    virtual void viewCalc(u32) = 0;

    JSULink<MVActor> mLink;
};

// TODO
class MVCamera;
class MVAmbient;
class MVChaseLight;
class MVDrawBuffer;


class MdlViewer { // Autogenerated
public:
    MdlViewer(); // 0x801d98cc
    void reset(); // 0x801d99cc
    void calc(); // 0x801d9a20
    void draw(); // 0x801d9aa0
    void append(MVActor *); // 0x801d9b04
    void setCurViewNoActor(u32); // 0x801d9b4c
    void calcActor(); // 0x801d9ca8
    void updateActor(); // 0x801d9d2c
    void viewCalcActor(u32); // 0x801d9db0
    // Inline/Unused
    // void ~MdlViewer();
    // void appendHio(HioNode *);
    // Inline
    void getCamera(); // 0x801d94a0
private:
    int _0; //
    MVCamera *mCamera; // 04
    MVAmbient *mAmbient; // 08
    MVChaseLight *mChaseLight; // 0C
    MVDrawBuffer *mDrawBuffer; // 10
    JSUList<MVActor> mActorList; // 14
}; // class MdlViewer

#endif