#ifndef MOVIEPLAYER_H
#define MOVIEPLAYER_H

#include "kartLocale.h"
#include "JSystem/JKernel/JKRHeap.h"

class MoviePlayer
{ // Autogenerated
public:
    // Global
    void create(JKRHeap *);                            // 0x801d8178
    MoviePlayer(VideoMode, VideoFrameMode, JKRHeap *); // 0x801d81e4
    ~MoviePlayer();                                    // 0x801d8314
    void reset();                                      // 0x801d838c
    void calc();                                       // 0x801d840c
    void draw();                                       // 0x801d842c
    void drawDone();                                   // 0x801d8498
    void quit();                                       // 0x801d84b8
    void play();                                       // 0x801d84f4
    void replay();                                     // 0x801d8534
    void pause();                                      // 0x801d8560
    void audioFadeOut(int);                            // 0x801d858c
    void getFrameNumber();                             // 0x801d85bc
    // void cMovieFileNameTable;                          // 0x804147d0
    // void cMovie50FileNameTable;                        // 0x804147d4
    static MoviePlayer *sPlayer; // 0x80416848
    // void sMovieSelector;                               // 0x8041684c
    //  Inline/Unused
    //  void sIsDispInfo;
};     // class MoviePlayer
#endif // MOVIEPLAYER_H