#ifndef SCRNSHOT_H
#define SCRNSHOT_H

#include <dolphin/gx/GXEnum.h>

#include "types.h"

class ScrnShot { // Autogenerated
public:
    // Global
    int capture();
    // Inline/Unused
    static void createScrnShot(int, int, GXTexFmt);
    //void SysDebug::getDebugHeap() const;
    ScrnShot(int, int, GXTexFmt);
    //void HioMgr::appendRootChild(HioNode *);
    //void HioNode::appendChild(HioNode *);
    //void JSUTree<HioNode>::appendChild(JSUTree<HioNode> *);
    //void JSUList<HioNode>::append(JSULink<HioNode> *);
    //void HIMGetManager();
    //void HioMgr::getManager();
    //void convTextureToBitmap();
    static ScrnShot *sScrnShot;

private:
    int _0;
    int _4;
    u8 _8[4];
    void* _C;
    u8 _10[0x18 - 0x10];
    bool mMakeScrnShot;

}; // class ScrnShot
#endif // SCRNSHOT_H