#ifndef SIMPLEDRAWER_H
#define SIMPLEDRAWER_H

#include "Kaneshige/ExModel.h"

class SimpleDrawer
{ // Autogenerated
public:
    SimpleDrawer();                      // 0x801ba064
    void drawInit(ExModel *);            // 0x801ba07c
    void drawInit(J3DModelData *);       // 0x801ba14c
    void loadPreDrawSetting();           // 0x801ba1b4
    static bool sEnableCheckHidding;     // 0x80414650
    static SimpleDrawer *sDrawingDrawer; // 0x804163e8
private:
    u32 _0;
    u8 _4;
    J3DMaterial *mDrawingMaterial; // 0x8
    bool mIsMatDrawOn;             // 0xc
}; // Size: unk

#endif // SIMPLEDRAWER_H