#ifndef LOGITECH_WHEELS_H
#define LOGITECH_WHEELS_H

#include "types.h"

class LGWheels
{ // Autogenerated
public:
    // Global
    LGWheels();                                     // 0x8007649c
    void InitVars(s32);                             // 0x80076520
    void ReadAll();                                 // 0x80076590
    void StopForce(s32, s32);                       // 0x8007664c
    bool IsConnected(s32);                          // 0x800769dc
    void IsPlaying(s32, s32);                       // 0x80076a00
    void PlayAutoCalibAndSpringForce(s32);          // 0x80076b3c
    void PlaySpringForce(s32, char, u8, s16);       // 0x80076c74
    void SameSpringForceParams(s32, char, u8, s16); // 0x80076e98
    void PlayConstantForce(s32, s16, u16);          // 0x80076ee0
    void SameConstantForceParams(s32, s16, u16);    // 0x800770d8
    void PlayDamperForce(s32, s16);                 // 0x8007710c
    void SameDamperForceParams(s32, s16);           // 0x80077310
    void PlayDirtRoadEffect(s32, u8);               // 0x80077330
    void SameDirtRoadEffectParams(s32, s16);        // 0x80077560
    void PlayBumpyRoadEffect(s32, u8);              // 0x80077580
    void StopBumpyRoadEffect(s32);                  // 0x800777b0
    void SameBumpyRoadEffectParams(s32, s16);       // 0x800777d4
    void PlaySlipperyRoadEffect(s32, s16);          // 0x800777f4
    void StopSlipperyRoadEffect(s32);               // 0x80077a90
    void SameSlipperyRoadEffectParams(s32, s16);    // 0x80077ab4
    void PlaySurfaceEffect(s32, u8, u8, u16);       // 0x80077ad4
    void SameSurfaceEffectParams(s32, u8, u8, u16); // 0x80077e20
    void PlayCarAirborne(s32);                      // 0x80077e64
    void StopCarAirborne(s32);                      // 0x8007804c
    // Inline/Unused
    // void ~LGWheels();
    // void ButtonTriggered(s32, u32);
    // void ButtonReleased(s32, u32);
    // void ButtonIsPressed(s32, u32);
    // void PedalsConnected(s32);
    // void PowerConnected(s32);
    // void SetOverallForceGain(s32, s32);
    // void GetOverallForceGain(s32);
    // void GenerateNonLinValues(s32, u8);
    // void StopSpringForce(s32);
    // void StopConstantForce(s32);
    // void StopDamperForce(s32);
    // void PlaySideCollisionForce(s32, s16, u16);
    // void SameSideCollisionForceParams(s32, s16, u16);
    // void PlayFrontalCollisionForce(s32, u8);
    // void SameFrontalCollisionForceParams(s32, s16);
    // void StopDirtRoadEffect(s32);
    // void StopSurfaceEffect(s32);
};     // class LGWheels
#endif // LOGITECH_WHEELS_H
