#ifndef GEOITEMBOX_H
#define GEOITEMBOX_H

#include "JSystem/JGeometry/Matrix.h"

#include "Sato/stMath.h"
#include "Sato/GeographyObj.h"

class RotAnimationObj {
public:
    RotAnimationObj();

    void resetRotAnimation(stRandom *);
    void setModelXYZDir(const JGeometry::TVec3f &, const JGeometry::TVec3f &, const JGeometry::TVec3f &);
    void calcRotAnimation(JGeometry::TPos3f &);
private:
    JGeometry::TPos3f mRot;
};

class GeoItemBox : public GeographyObj { // Autogenerated
public:
    GeoItemBox(const CrsData::SObject &); // 0x8022df80
    GeoItemBox(); // 0x8022e008

    virtual void *getAnmTbl(); // 0x8022e0e8
    virtual u32 getSizeAnmTbl(); // 0x8022e170
    virtual void reset(); // 0x8022e208
    virtual void createModel(JKRSolidHeap *, u32); // 0x8022e394
    virtual void createColModel(J3DModelData *); // 0x8022e3dc
    virtual void createShadowModel(JKRSolidHeap *, u32); // 0x8022e404
    virtual const char *getBmdFileName(); // 0x8022e500
    virtual const char *getShadowBmdFileName(); // 0x8022e590
    virtual void calc(); // 0x8022e5b8
    virtual void doKartColCallBack(int); // 0x8022ec34

    void initialize(); // 0x8022e094
    void rotAnimation(); // 0x8022e5ec
    void doMode(); // 0x8022e830
    void doInactive(); // 0x8022e88c
    void doOpening(); // 0x8022ea40
    void doEnding(); // 0x8022eb20
    void doHide(); // 0x8022ebdc
    void setInactiveTime(); // 0x8022e1fc    
    
    static const char *getBmdName(); // 0x8022e448
    static const char * getShadowBmdName(); // 0x8022e4d8
    static u8 getInactiveTime(); // 0x8022ee6c

    //static sMatAnmTable; // 0x804148fc
    //void sMatAnmTable4P; // 0x80414904
    //void sMatAnmTableMiniBomb; // 0x8041490c

    // Inline/Unused
    //void resetRot();
    //void getBmdFilePtr();
    //void setItemSlot(int);
    //void setEffect(bool);

    // Virtual Inlines
    virtual void setOpeningPos() {} // 0x8022ea3c
    virtual ~GeoItemBox() {} // 0x8022efd4
    virtual u32 getJ3DModelDataTevStageNum() const { return 0x40000; } // 0x8022fa58

private:
    // TODO
}; // class GeoItemBox

class GeoDoubleItemBox : public GeoItemBox {
public:
    GeoDoubleItemBox();
    virtual ~GeoDoubleItemBox() {} // 0x8022f9c8
    virtual const char *ggetBmdFileName();
    virtual void createColModel(J3DModelData *);
    virtual void *getAnmTbl();
    virtual u32 getSizeAnmTbl();
    
    //static sDoubleMatAnmTable;
    //static sDoubleMatAnmTable4P;
    //static sDoubleMatAnmTableMiniBomb;
};

class GeoF_ItemBox : public GeoItemBox {
public:
    GeoF_ItemBox(const CrsData::SObject &);
    virtual ~GeoF_ItemBox() {} // 0x8022fa60

    virtual void reset();
    virtual void calc();
};

#endif // GEOITEMBOX_H
