#ifndef GEOITEMBOX_H
#define GEOITEMBOX_H

#include "JSystem/JGeometry/Matrix.h"

#include "JSystem/JGeometry/Vec.h"
#include "JSystem/JParticle/JPAEmitter.h"
#include "Sato/Objects/GeoObjPathMove.h"
#include "Sato/stMath.h"
#include "Sato/GeographyObj.h"

class RotAnimationObj {
public:
    RotAnimationObj();

    void resetRotAnimation(stRandom *);
    void setModelXYZDir(const JGeometry::TVec3f &, const JGeometry::TVec3f &, const JGeometry::TVec3f &);
    void calcRotAnimation(JGeometry::TPos3f &);
protected:
    // TODO: "correct" names
    JGeometry::TVec3f mModelZDir; // 00
    JGeometry::TVec3f mModelYDir; // 0c
    JGeometry::TVec3f mModelXDir; // 18
    s16 mRandDir; // 24
    f32 _28;
    f32 _2c;
};

class GeoItemBox : public GeographyObj, RotAnimationObj { // Autogenerated
public:
    GeoItemBox(const CrsData::SObject &); // 0x8022df80
    GeoItemBox(); // 0x8022e008

    virtual GeoAnmTableEntry *getAnmTbl(); // 0x8022e0e8
    virtual u16 getSizeAnmTbl(); // 0x8022e170
    virtual void reset(); // 0x8022e208
    virtual void createModel(JKRSolidHeap *, u32); // 0x8022e394
    virtual void createColModel(J3DModelData *); // 0x8022e3dc
    virtual void createShadowModel(JKRSolidHeap *, u32); // 0x8022e404
    virtual const char *getBmdFileName(); // 0x8022e500
    virtual const char *getShadowBmdFileName(); // 0x8022e590
    virtual void calc(); // 0x8022e5b8
    virtual void doKartColCallBack(int); // 0x8022ec34

    void initialize(); // 0x8022e094
    void rotAnimation(); // 0x8022e5ec
    void doMode(); // 0x8022e830
    void doInactive(); // 0x8022e88c
    void doOpening(); // 0x8022ea40
    void doEnding(); // 0x8022eb20
    void doHide(); // 0x8022ebdc
    void setInactiveTime(); // 0x8022e1fc    
    
    static const char *getBmdName(); // 0x8022e448
    static const char *getShadowBmdName(); // 0x8022e4d8
    static u8 getInactiveTime(); // 0x8022ee6c

    // Inline/Unused
    void resetRot();
    const char *getBmdFilePtr();
    void setItemSlot(int);
    void setEffect(bool);

    // Virtual Inlines
    virtual void setOpeningPos() {} // 0x8022ea3c
    virtual ~GeoItemBox() {} // 0x8022efd4
    virtual u32 getJ3DModelDataTevStageNum() const { return 0x40000; } // 0x8022fa58

    static GeoAnmTableEntry sMatAnmTable;
    static GeoAnmTableEntry sMatAnmTable4P;
    static GeoAnmTableEntry sMatAnmTableMiniBomb;

private:
    int mMode;                 // 17c
    int _180;                  // is holding item?
    CrsGround mGround;         // 184
    int mRank;                 // 1e4
    u8 _1e8;                   // unused variable? only gets written to
    JPABaseEmitter *mpEmitter[2]; // 1ec
    int mKartIdx;              // 1f4
    bool _1f8;                 //
    JGeometry::TVec3f mObjPos; // 1fc
}; // class GeoItemBox

class GeoDoubleItemBox : public GeoItemBox {
public:
    GeoDoubleItemBox();
    virtual ~GeoDoubleItemBox() {} // 0x8022f9c8
    virtual const char *getBmdFileName();
    virtual void createColModel(J3DModelData *);
    virtual GeoAnmTableEntry *getAnmTbl();
    virtual u16 getSizeAnmTbl();
    

    static GeoAnmTableEntry sDoubleMatAnmTable;
    static GeoAnmTableEntry sDoubleMatAnmTable4P;
    static GeoAnmTableEntry sDoubleMatAnmTableMiniBomb;
};

class GeoF_ItemBox : public GeoItemBox {
public:
    GeoF_ItemBox(const CrsData::SObject &);
    virtual ~GeoF_ItemBox() {} // 0x8022fa60

    virtual void reset();
    virtual void calc();

private:
    GeoObjPathMove *mMove;
    u8 _20c;
};

#endif // GEOITEMBOX_H
