#ifndef GEOJUMPNARROW_H
#define GEOJUMPNARROW_H

#include "Sato/GeographyObj.h"

class GeoJumpNarrow : public ExGeographyObj { // Autogenerated
public:
    // Global
    GeoJumpNarrow(const CrsData::SObject &); // 0x8022d928
    virtual void reset(); // 0x8022d994
    virtual void createColModel(J3DModelData *); // 0x8022d9c8
    virtual const char *getBmdFileName(); // 0x8022dabc
    virtual void calc(); // 0x8022dae4
    // Inline
    virtual ~GeoJumpNarrow() {} // 0x8022dae8
}; // class GeoJumpNarrow
#endif // GEOJUMPNARROW_H
