#ifndef GEORFLOWER_H
#define GEORFLOWER_H

#include "Sato/GeographyObj.h"

class GeoRFlower : public GeographyObj { // Autogenerated
public:
    // Inline/Unused
    GeoRFlower(const CrsData::SObject &);
    ~GeoRFlower() {}
    void reset();
    void createColModel(J3DModelData *);
    virtual const char *getBmdFileName();
    void calc();
}; // class GeoRFlower


class GeoMarioFlower1 : public GeographyObj {
    GeoMarioFlower1(const CrsData::SObject &);
    ~GeoMarioFlower1() {}
    void reset();
    void loadAnimation();
    void createColModel(J3DModelData *);
    void createModel(JKRSolidHeap *, u32);
    virtual const char* getBmdFileName();
    void calc();
    static J3DAnmTransform *sMarioFlower1BckAnmTrans;
    static J3DMtxCalc *sMarioFlower1BckMtxCalc;
};


#endif // GEORFLOWER_H
