#ifndef GEOTREE_H
#define GEOTREE_H

#include "Sato/GeographyObj.h"

class GeoTree : public GeographyObj { // Autogenerated
public:
    GeoTree(const CrsData::SObject &);

    virtual void reset(); // 0x8022b15c
    virtual void createColModel(J3DModelData *); // 0x8022b190
    virtual const char *getBmdFileName(); // 0x8022b1b8
    virtual void calc(); // 0x8022b1e0
    bool availBckAnm(); // 0x8022b1e4

    // Inline
    virtual ~GeoTree() {} // 0x8022b268
}; // class GeoTree

class GeoMarioTree1 : public GeoTree {
public:
    GeoMarioTree1(const CrsData::SObject &);
    ~GeoMarioTree1() {}
    
    virtual void reset();
    virtual void createColModel(J3DModelData *);
    virtual void createModel(JKRSolidHeap *, u32);
    virtual const char *getBmdFileName();
    virtual void calc();
    virtual void doKartColCallBack(int);
    virtual GeoAnmTableEntry *getAnmTbl();
    virtual  u32 getSizeAnmTbl();

    static GeoAnmTableEntry sBckAnmTable[1];
};

class GeoMarioKinoko1 : public GeoTree {
public:
    GeoMarioKinoko1(const CrsData::SObject &);
    ~GeoMarioKinoko1() {} // 0x8022b684
    virtual void createColModel(J3DModelData *);
    virtual const char *getBmdFileName();
    virtual void calc();
};

#endif // GEOTREE_H
