#ifndef GEOBOMBCAR_H
#define GEOBOMBCAR_H

#include "JSystem/JParticle/JPAEmitter.h"
#include "Kaneshige/Objects/GeoCar.h"
#include "Kaneshige/Objects/GeoCarShadow.h"
#include "Sato/J3DAnmObject.h"
#include "Sato/ObjUtility.h"

class GeoBombCar : public GeoCar
{ // Autogenerated
public:
    GeoBombCar(const CrsData::SObject &);             // 0x801c0914, overide
    virtual void reset();                             // 0x801c0ac0, overide
    virtual void createModel(JKRSolidHeap *, u32);    // 0x801c0b2c, overide
    virtual void createColModel(J3DModelData *);      // 0x801c0b94, overide
    virtual const Vec &getTirePosOffset(int);         // 0x801c0be0, overide
    virtual void loadAnimation();                     // 0x801c0c70, overide
    virtual void setCurrentViewNo(u32);               // 0x801c0cc0, overide
    virtual void update();                            // 0x801c0d20, overide
    virtual void simpleDraw(u32);                     // 0x801c0d64, overide
    virtual void calc();                              // 0x801c0db8, overide
    virtual void hitKart(int);                        // 0x801c0f30, overide
    virtual void hitItemBomb();                       // 0x801c0f8c, overide
    virtual void hitItemWanWan();                     // 0x801c0fc0, overide
    virtual void hitItemGTurtleBig();                 // 0x801c0fe8, overide
    virtual void hitItemGTurtle();                    // 0x801c1008, overide
    virtual void hitItemRTurtle();                    // 0x801c1028, overide
    virtual void hitItemFireBall();                   // 0x801c1048, overide
    virtual void hitItemYoshiEgg();                   // 0x801c1068, overide
    virtual void initCallBackDeath();                 // 0x801c1088, overide
    virtual void doCallBackDeath();                   // 0x801c115c, overide

    // Inline

    // Inline/Unused
    // void initCallBackMove();
    // static u32 sCreateNum;
    virtual const char *getBmdFileName() { return "/Objects/Car_Bomb1.bmd"; } // 801c1338
    virtual u32 getSoundCarType() const { return 0; }                         // 0x801c1344
    virtual bool isBlast() { return mIsBlast; };                              // 0x801c134c
    //virtual ~GeoBombCar() {}                                                // 0x801c12c8
private:
    static const Vec sTireOfsTable[4];         // 0x80378e28
    static s16 sMaxBombReactFrame;             // 0x804146a0
    static J3DAnmTextureSRTKey *sTireBtkAnm;   // 0x80416438
    // TODO
    GeoBombShadow *mShadow;
    ObjColBase *mColBounds;
    BombEffectObj *mEffObj;
    JPABaseEmitter *_26c;
    bool mIsBlast; // 270
    int _274;
    int _278;
    int _27c;
    J3DAnmObjMaterial mMat;
}; // class GeoBombCar

#endif // GEOBOMBCAR_H
