#ifndef GEOCARSHADOW_H
#define GEOCARSHADOW_H

#include "Kaneshige/Objects/GeoCar.h"

class GeoCarShadow : public GeographyObj
{ // Autogenerated
public:
    GeoCarShadow();                                                        // 0x801c3be4
    GeoCarShadow(u32);                                                     // 0x801c3c84
    virtual void reset();                                                  // 0x801c3d10
    virtual const char *getBmdFileName();                                        // 0x801c3d90
    void setCarPose(const JGeometry::TVec3f &, const JGeometry::TVec3f &); // 0x801c3db8
    // Inline
    virtual ~GeoCarShadow() {} // 0x801c3ec0
    virtual void calc()
    { /*_40.set(_14c); */
    } // 0x801c403c
};    // class GeoCarShadow

class GeoHanaBodyShadow : public GeoCarShadow
{
public:
    GeoHanaBodyShadow();
    virtual ~GeoHanaBodyShadow() {}                                               // 0x801c3fd8
    virtual const char *getBmdFileName() { return "/Objects/Car_Hana1BodyShadow.bmd"; } // 0x801c4030
private:
    // TODO
};

class GeoHanaShadow : public GeoCarShadow
{
public:
    GeoHanaShadow();
    virtual ~GeoHanaShadow() {}                                               // 0x801c4068
    virtual const char *getBmdFileName() { return "/Objects/Car_Hana1Shadow.bmd"; } // 0x801c40c0
private:
    // TODO
};

class GeoBombShadow : public GeoCarShadow
{
public:
    GeoBombShadow();
    virtual ~GeoBombShadow() {}                                               // 0x801c4130
    virtual const char *getBmdFileName() { return "/Objects/Car_Bomb1Shadow.bmd"; } // 0x801c4188
private:
    // TODO
};

class GeoKinoShadow : public GeoCarShadow
{
public:
    GeoKinoShadow();
    virtual ~GeoKinoShadow();                                                   // 0x801c40cc
    virtual const char *getBmdFileName() { return "/Objects/Car_Kinoko1Shadow.bmd"; } // 0x801c4124
private:
    // TODO
};

#endif // GEOCARSHADOW_H
