#ifndef GEOCARSHADOW_H
#define GEOCARSHADOW_H

#include "JSystem/JGeometry/Vec.h"
#include "Sato/GeographyObj.h"

class GeoCarShadow : public GeographyObj
{ // Autogenerated
public:
    GeoCarShadow();                                                        // 0x801c3be4
    GeoCarShadow(u32 id);                                                  // 0x801c3c84
    virtual void reset();                                                  // 0x801c3d10
    virtual const char *getBmdFileName();                                  // 0x801c3d90
    void setCarPose(const JGeometry::TVec3f &, const JGeometry::TVec3f &); // 0x801c3db8
    // Inline
    virtual ~GeoCarShadow() {} // 0x801c3ec0
    virtual void calc()
    {
        mScale.set(mShadowScale);
    } // 0x801c403c

    void setBaseScale(JGeometry::TVec3f &scale) { mShadowScale.set(scale); }

    JGeometry::TVec3f mShadowScale;
    JGeometry::TVec3f mFrDir;
    JGeometry::TVec3f mUpDir;
    JGeometry::TVec3f mLfDir;
}; // class GeoCarShadow

class GeoHanaBodyShadow : public GeoCarShadow
{
public:
    GeoHanaBodyShadow();
    virtual ~GeoHanaBodyShadow() {}                                               // 0x801c3fd8
    virtual const char *getBmdFileName() { return "/Objects/Car_Hana1BodyShadow.bmd"; } // 0x801c4030
};

class GeoHanaShadow : public GeoCarShadow
{
public:
    GeoHanaShadow();
    virtual ~GeoHanaShadow() {}                                               // 0x801c4068
    virtual const char *getBmdFileName() { return "/Objects/Car_Hana1Shadow.bmd"; } // 0x801c40c0
};

class GeoBombShadow : public GeoCarShadow
{
public:
    GeoBombShadow();
    virtual ~GeoBombShadow() {}                                                      // 0x801c4130
    virtual const char *getBmdFileName() { return "/Objects/Car_Bomb1Shadow.bmd"; } // 0x801c4188
};

class GeoKinoShadow : public GeoCarShadow
{
public:
    GeoKinoShadow();
    virtual ~GeoKinoShadow() {}                                                       // 0x801c40cc
    virtual const char *getBmdFileName() { return "/Objects/Car_Kinoko1Shadow.bmd"; } // 0x801c4124
};

#endif // GEOCARSHADOW_H
