#ifndef GEOITEMGEN_H
#define GEOITEMGEN_H

#include "Sato/GeographyObj.h"
#include "Sato/StateObserver.h"

class GeoItemGen : public GeographyObj, StateObserver
{ // Autogenerated
public:
    GeoItemGen(const CrsData::SObject &);        // 0x801c507c
    virtual void reset();                        // 0x801c50f4
    virtual void createColModel(J3DModelData *); // 0x801c5364
    void setItemKind();                          // 0x801c53a0
    void checkKartCollision();                   // 0x801c5488
    virtual void calc();                         // 0x801c577c
    void initFuncWait();                         // 0x801c5930
    void doFuncWait();                           // 0x801c5934
    // Inline/Unused
    // void sDummyKartHit;
    // Inline
    virtual void InitExec() /*__ptmf_scall(this, FindStateFunc(getState()), &sTable, 1);*/; // 0x801c57c8
    virtual void MoveExec() /*__ptmf_scall(this, FindStateFunc(getState()), &sTable, 1);*/; // 0x801c58dc
    virtual ~GeoItemGen() {}                                                          // 0x801c5938
private:
    static int sRandomTable[4]; // 0x80379358
    // void sTable;                          // 0x803970b0
    static s16 sNextOccurTime;                                                      // 0x804146e0
    static s16 sOccurLimitSpeed;                                                    // 0x804146e2
};                                                                                  // class GeoItemGen
// void ItemObj::setOwnerNum(int) // ItemObj.h; // 0x801c5758
// void GeographyObj::getBmdFileName() // GeographyObj.h; // 0x801c59a8
#endif // GEOITEMGEN_H