#ifndef GEOKINOJII_H
#define GEOKINOJII_H

#include "JSystem/JGeometry/Vec.h"
#include "Sato/GeographyObj.h"
#include "Sato/J3DAnmObject.h"
#include "Sato/StateObserver.h"

class GeoKinojii : public GeographyObj, public StateObserver { // Autogenerated
public:
    GeoKinojii(const CrsData::SObject &obj); // 0x801d0fa8
    void reset(); // 0x801d1038
    void resetAnimation(); // 0x801d1184
    void loadAnimation(); // 0x801d11dc
    void createModel(JKRSolidHeap *, u32); // 0x801d12cc
    void setCurrentViewNo(u32); // 0x801d1398
    void calc(); // 0x801d1414
    void update(); // 0x801d1460
    void initFuncWait(); // 0x801d160c
    void doFuncWait(); // 0x801d1610
    void InitExec(); // 0x801d14a4
    void MoveExec(); // 0x801d15b8

    // Inline
    //virtual ~GeoKinojii(); // 0x801d17d0
    const char *getBmdFileName() { return "/Objects/kinojii.bmd"; } // 0x801d184c
    virtual u32 getJ3DModelDataTevStageNum() const { return 0x20020; } // 0x801d1858

private:
    static StateFuncSet<GeoKinojii> sTable[1]; // 0x80397b88
    static s16 sWinkRate;                      // 0x80414790
    static s16 sWinkInterval;                  // 0x80414792
    static J3DAnmTransform *sBcaAnmTrans;      // 0x80416550
    static J3DMtxCalc *sBcaMtxCalc;            // 0x80416554
    static J3DAnmTexPattern *sWinkBtpAnm;      // 0x80416558

    // Unused
    static s16 sCreateNum;

    JGeometry::TVec3f mFrDir;
    JGeometry::TVec3f mUpDir;
    JGeometry::TVec3f mLfDir;
    JGeometry::TVec3f _17c;
    s16 mKartNo;
    s16 mWinkTimer;
    J3DAnmObjMaterial mMat;
}; // class GeoKinojii

#endif // GEOKINOJII_H
