#ifndef GEOKINOCAR_H
#define GEOKINOCAR_H

#include "Kaneshige/Objects/GeoCarShadow.h"
#include "Kaneshige/Objects/GeoCar.h"

class GeoKinoCar : public GeoCar
{ // Autogenerated
public:
    GeoKinoCar(const CrsData::SObject &);          // 0x801c1448
    virtual void reset();                          // 0x801c15cc
    virtual void createModel(JKRSolidHeap *, u32); // 0x801c1610
    virtual void createColModel(J3DModelData *);   // 0x801c1678
    virtual void loadAnimation();                  // 0x801c16b4
    virtual const Vec &getTirePosOffset(int);      // 0x801c1704
    virtual void calc();                           // 0x801c1794
    virtual void simpleDraw(u32);                  // 0x801c1818
    virtual void hitKart(int);                     // 0x801c186c
    void occurKinoko(const JGeometry::TVec3f &);   // 0x801c1970
    void occurKinoko(ItemObj *);                   // 0x801c1a6c
    virtual void hitItemGTurtle();                 // 0x801c1ad4
    virtual void hitItemGTurtleBig();              // 0x801c1b0c
    virtual void hitItemYoshiEgg();                // 0x801c1b54
    virtual void hitItemRTurtle();                 // 0x801c1b8c

    // Inline
    //virtual ~GeoKinoCar() {}                                              // 0x801c1bc4
    virtual const char *getBmdFileName() { return "/Objects/Car_Kinoko1.bmd"; } // 0x801c1c34
private:
    // Unused
    static u16 sCreateNum;

    static const Vec sTireOfsTable[4];       // 0x80378ed8
    static s16 sOccurLimitSpeed;             // 0x804146a8
    static s16 sNextOccurTime;               // 0x804146aa
    static f32 sOccurVel0;                   // 0x804146ac
    static J3DAnmTextureSRTKey *sTireBtkAnm; // 0x80416440
    
    GeoKinoShadow *mShadow;
    s16 mTimer;
    J3DAnmObjMaterial mTireMat;
};                                           // class GeoKinoCar

#endif // GEOKINOCAR_H
