#ifndef GEOSHINE_H
#define GEOSHINE_H

#include "JSystem/JGeometry/Vec.h"
#include "Sato/GeographyObj.h"

class GeoRabbitMark;

class GeoShine : public GeographyObj { // Autogenerated
public:
    GeoShine();                            // 0x801d50fc
    void reset();                          // 0x801d5190
    void calcShadowModel();                // 0x801d53d4
    const char *getShadowBmdFileName();    // 0x801d559c
    void loadAnimation();                  // 0x801d55bc
    void createColModel(J3DModelData *);   // 0x801d55c0
    void createModel(JKRSolidHeap *, u32); // 0x801d55e8
    void simpleDraw(u32);                  // 0x801d55ec
    void calc();                           // 0x801d5618
    void move();                           // 0x801d561c
    void startFastRot();                   // 0x801d5a84

    // Inline
    virtual ~GeoShine() {} // 0x801d5aac
    const char *getBmdFileName() { return "/Objects/MiniGame_shine.bmd"; } // 0x801d5b04

    void setMark(GeoRabbitMark *mark) { mMark = mark; }
    void setConsoleNo(u32 no) { mConsoleNo = no; } 
    void enableWinEffect() { mWinEffectOn = true; }

private:
    static const char *sNormalEmitterName[3]; // 0x803980b8
    static const f32 sShadowScale;            // 0x803fc288
    static const char *sWinnerEmitterName[2]; // 0x804147a8
    static f32 sScalingNearZ;                 // 0x804147b0
    static f32 sScalingFarZ;                  // 0x804147b4
    static f32 sMaxScale;                     // 0x804147b8
    static f32 sRotAnmMaxVel;                 // 0x804147bc
    static f32 sRotAnmVelNormal;              // 0x804147c0
    static f32 sRotAnmFastV0;                 // 0x804147c4
    static f32 sRotAnmResist;                 // 0x804147c8

    GeoRabbitMark *mMark;
    u32 mConsoleNo;
    JGeometry::TVec3f _154;
    JGeometry::TVec3f _160;
    JGeometry::TVec3f _16c;
    JGeometry::TVec3f _178;
    JGeometry::TVec3f _184;
    JGeometry::TVec3f _190;
    u8 _19c[0x1a4 - 0x19c];
    bool mWinEffectOn;
    u8 _1a5[0x1b0 - 0x1a5];
}; // class GeoShine

// Inline Functions called in TU
// void ViewCtrlModel::setVisible(unsigned long) // ViewCtrlModel.h; // 0x801d5344
// void ViewCtrlModel::clrVisibleAll() // ViewCtrlModel.h; // 0x801d535c
// void ViewCtrlModel::setDetailFlg() // ViewCtrlModel.h; // 0x801d536c
// void GeoRabbitMark::getPosition(JGeometry::TVec3<float> *) // GeoRabbitMark.h; // 0x801d53a8
// void ViewCtrlModel::isInvisibleAll() // ViewCtrlModel.h; // 0x801d5588
// void JPABaseEmitter::setGlobalScale(const JGeometry::TVec3<float> &) // JPABaseEmitter.h; // 0x801d59dc
// void GeoRabbitMark::getFootLength() const // GeoRabbitMark.h; // 0x801d5a2c
// void GeoRabbitMark::getMarkScale() const // GeoRabbitMark.h; // 0x801d5a44
// void GeoRabbitMark::getFootPosition(JGeometry::TVec3<float> *) // GeoRabbitMark.h; // 0x801d5a4c

#endif // GEOSHINE_H
