#ifndef EFFECTSCREEN_H
#define EFFECTSCREEN_H

#include "types.h"
#include <JSystem/JGeometry/Vec.h>

class EffectScreen { // Autogenerated
public:
    enum ScreenKind {
        Kind_0,
        Kind_1,
    };
    EffectScreen(); // 0x8026c694
    void doDemo(); // 0x8026c6a8
    void doThunder(); // 0x8026c740
    void doBombExplosion(); // 0x8026c834
    void doExplosion(); // 0x8026c940
    // Inline/Unused
    //void setFunction(const ScreenKind &);
    //void checkCamDrawing() const;
    //void checkFrame();
    //void initThunder();
    //void initDemo();
    //void setBombColorIndex(u8);
    //void initBombExplosion(float, u8);
    //void initExplosion(float);
    //void calc();
    //void draw();
    //void EffectScreenMgr::initDraw();
    //void EffectScreenMgr::drawScreens(u32);
}; // class EffectScreen

class EffectScreenMgr
{
public:
    EffectScreenMgr();
    void calc();
    void reset();
    void flashThunder(int);
    void flashBombExplosion(u8, const JGeometry::TVec3f &);
    void startDemoScreen();
    void draw_middle(u32);
    void draw(u32);
    void draw_demoScreen(u32);

    bool IsContinue(EffectScreen::ScreenKind); // 0x8026d368

    static void createMgr() { ThisMgr = new EffectScreenMgr(); }
    static EffectScreenMgr * getThis() { return ThisMgr; }

    static EffectScreenMgr *ThisMgr;
    u8 _00[0xd0];
};

inline void CreateEfctScreenMgr() {
    EffectScreenMgr::createMgr();
}

inline EffectScreenMgr *GetEfctScreenMgr() {
    return EffectScreenMgr::getThis();
}

#endif
