#ifndef GEOGRAPHYOBJ_H
#define GEOGRAPHYOBJ_H

#include <JSystem/JKernel/JKRHeap.h>
#include <JSystem/J3D/J3DModel.h>
#include "Kaneshige/Course/CrsData.h"
#include "Sato/ItemObj.h"

// TODO: Remove Forward declarations
class ObjColBase; // ObjCollision.h

class GeoObjSupervisor
{
public:
    GeoObjSupervisor() : mLink(this), mLink2(this) {} // 0x801ba468

    // Vtable 0x0
    virtual ~GeoObjSupervisor() {}   // 0x801ba3b4
    virtual void load() {}           // 0x801bcfa4
    virtual void reset() = 0;        // 0x0
    virtual void calc() = 0;         // 0x0
    virtual void thunderDownAll() {} // 0x801bcfa8
    virtual void createModel(JKRSolidHeap *, u32);

private:
    JSULink<GeoObjSupervisor> mLink;
    JSULink<GeoObjSupervisor> mLink2;
};

// TODO: replace void with correct return types
class GeographyObj
{ // Autogenerated
public:
    GeographyObj(const CrsData::SObject &);                                                     // 0x8022937c
    GeographyObj(u32);                                                                          // 0x80229450
    void setDefaultItemReaction();                                                              // 0x80229508
    void calc_norm();                                                                           // 0x802295f0
    void update_norm();                                                                         // 0x80229630
    void loadShadowModel(J3DModelData *, u32);                                                  // 0x8022972c
    void getAssignedModelXYZdir(JGeometry::TVec3f *, JGeometry::TVec3f *, JGeometry::TVec3f *); // 0x80229838
    void getAssignedModelMatrix(Mtx);                                                           // 0x80229968
    void resetObject();                                                                         // 0x80229bcc
    void IsHitKart(const JGeometry::TVec3f &, f32, JGeometry::TVec3f *);                        // 0x80229df4
    void IsHitObject(const JGeometry::TVec3f &, ObjColBase *);                                  // 0x80229f98
    void setIsHitKartFlg(int);                                                                  // 0x8022a074
    void clrIsHitKartSoundFlg(int);                                                             // 0x8022a0c4
    bool tstUserFlg1(int kart_index) const;                                                     // 0x8022a0ec
    void clrUserFlg1(int);                                                                      // 0x8022a190
    void setUserFlg1(int);                                                                      // 0x8022a230
    void getHitSoundDegree();                                                                   // 0x8022a2d0                                                                   
    void createMultiBoundsPtrAll(u8);                                                           // 0x8022a314
    void calcBoundsGlPos();                                                                     // 0x8022a420
    void createBoundsSphere(f32, f32);                                                          // 0x8022a57c
    void createMultiBoundsSphere(u8, f32, f32);                                                 // 0x8022a66c
    void createBoundsCylinder(J3DModelData *, f32, f32);                                        // 0x8022a6fc
    void createBoundsCylinder(f32, f32, f32);                                                   // 0x8022a81c
    void createMultiBoundsCylinder(u8, J3DModelData *, f32, f32);                               // 0x8022a934
    void createBoundsCube(J3DModelData *);                                                      // 0x8022aa04
    void setColObjPos(const JGeometry::TVec3f &, u8);                                           // 0x8022ab20
    u32 getGeoRnd();                                                                            // 0x8022ac14
    void moveShadowModel();                                                                     // 0x8022ac38
    void createSoundMgr();                                                                      // 0x8022acec
    f32 getColScaleRadius();                                                                    // 0x8022ad44
    void getAxisMaxScale();                                                                     // 0x8022adb4
    void lockMdl();                                                                             // 0x8022ae58
    void getSRTMtx(Mtx m);                                                                      // 0x8022ae88
    void setBoundScaleAll();                                                                    // 0x8022aef0
    f32 getAllBoundDepth();                                                                     // 0x8022af54
    void setObjData(const CrsData::SObject &, bool);                                            // 0x8022af94
    // Inline/Unused
    void getAssignedModelZdir(JGeometry::TVec3f *);
    void findVtxPosMaxY(J3DModelData *, JGeometry::TVec3f &, JGeometry::TVec3f &);
    void newSingleObjColSphere(f32, f32);
    void newSingleObjColSphere(J3DModelData *);
    void newSingleObjColCylinder(J3DModelData *, f32, f32);
    void newSingleObjColCylinder(f32, f32, f32);
    void initSingleBound();
    void createMultiBoundsSphere(u8, J3DModelData *);
    void createMultiBoundsCylinder(u8, f32, f32, f32);
    void setLODBias();
    void getColRadius();

    // Vtable
    virtual ~GeographyObj() {}                                                                // 0x801b48cc, TODO?
    virtual void loadmodel(J3DModelData *modelData);                                          // 0x801b4c28, TODO
    virtual void loadAnimation() {}                                                           // 0x801b4c74                                                     // 0x801b4c74
    virtual ShadowModel::ShadowKind getShadowKind() { return ShadowModel::cShadowKind_Geo; }; // 0x801b4c78
    virtual void createModel(JKRSolidHeap *heap, u32) {}                                      // 0x801b4c80, TODO
    virtual void configAnimationMode() {}                                                     // 0x801b4ce8
    virtual void createShadowModel(JKRSolidHeap *heap, u32);                                  // 0x8022ab60
    virtual void initByKind() {}                                                              // 0x801b4cec
    virtual void reset() { resetObject(); }                                                   // 0x801d76ac
    virtual void calc() = 0;                                                                  // 0x0
    virtual void update();                                                                    // 0x80229684
    virtual void viewCalc(u32);                                                               // 0x802296d4
    virtual void simpleDraw(u32);                                                             // 0x8022addc
    virtual void setCurrentViewNo(u32);                                                       // 0x80229700
    virtual u32 getMotorType() const { return 1; }                                            // 0x801b4cf0, probably an Enum
    virtual u32 getSoundID() const;                                                           // 0x8022a308, probably a define
    virtual char *getBmdFileName() { return nullptr; }                                        // 0x801c59a8
    virtual char *getShadowBmdFileName() { return nullptr; }                                  // 0x801b4cf8
    virtual u32 getJ3DModelDataTevStageNum() const { return 0x20000; }                        // 0x801b4d00
    virtual void createColModel(J3DModelData *);                                              // 0x8022ab5c
    virtual void createBoundsSphere(J3DModelData *);                                          // 0x8022a498
    virtual void *getAnmTbl() { return nullptr; }                                             // 0x801b4d08
    virtual u32 getSizeAnmTbl() { return 0; }                                                 // 0x801b4d10
    virtual GeoObjSupervisor *getSupervisor() { return nullptr; }                             // 0x801b4d18
    virtual void getItemThrowDirPow(JGeometry::TVec3f *, f32 *, const ItemObj &);             // 0x8022af8c
    virtual void getKartThrowDirPow(JGeometry::TVec3f *, f32 *, int);                         // 0x8022af90
    virtual void makeSharedDL() {}                                                            // 0x801b4d20, TODO
    virtual void doKartColCallBack(int);                                                      // 0x8022ace8
    virtual void initClassCreateNum();                                                        // 0x801b4d5c
    virtual void setModelMatrixAndScale();                                                    // 0x802297e0
private:
    // TODO
}; // class GeographyObj

#endif