#ifndef ITEMBANANA_H
#define ITEMBANANA_H

#include "Sato/ItemObj.h"

// TODO: virtual functions

class ItemBanana : public ItemObj
{ // Autogenerated
public:
    ItemBanana(u32);                                                      // 0x8025186c
    void reset();                                                         // 0x8025190c
    const char *getBmdFileName();                                         // 0x802519e8
    static void loadAnmData(J3DModelData *);                                     // 0x80251a10
    void createModel(JKRSolidHeap *, u32, u32);                           // 0x80251a88
    void getBckName(int);                                                 // 0x80251bf4
    void update();                                                        // 0x80251c40
    void doUniv();                                                        // 0x80251c88
    void checkAnmState();                                                 // 0x80251d98
    void initEquip();                                                     // 0x80252110
    void doEquip();                                                       // 0x802521ac
    void initRelease();                                                   // 0x802521d4
    void doRelease();                                                     // 0x802523dc
    void initSpRelease();                                                 // 0x80252478
    void doSpRelease();                                                   // 0x80252590
    void initDisappear();                                                 // 0x80252768
    void doDisappear();                                                   // 0x802528dc
    void doFall();                                                        // 0x802529b4
    void moveNormal(CrsGround &);                                         // 0x80252a10
    void getItemBoundRatio() const;                                       // 0x80252b6c
    void setAllUseBoundsScale();                                          // 0x80252b74
    void setAllUseInitReleaseVelMag();                                    // 0x80252ba4
    void checkKartColDisappear(int);                                      // 0x80252bbc
    void initOccur(const JGeometry::TVec3f &, const JGeometry::TVec3f &); // 0x80252bec
    void doSound(u32);                                                    // 0x80252c24

    static J3DAnmObjTrans *mAnmTrans[3]; // 0x803a05d8
    static J3DAnmTransform *mAnmCalc[3]; // 0x803a05e4
    static Vec sHandOffsetPos;           // 0x804118ec
    // Inline/Unused
    // void setInitReleaseParam();
    // void getBckName(int);
    // void getBtkName();
    // Inline
    void calcBaseRotQt();                // 0x80252470
    virtual ~ItemBanana();               // 0x80252cf0
    u32 getModelDataAppendLoadFlg();     // 0x80254938
    void createColModel(J3DModelData *); // 0x80254a60

    u8 _[0x2cc - 0x2b0];
}; // class ItemBanana

class ItemBananaBig : public ItemBanana
{
public:
    ItemBananaBig(u32);
    void reset();
    const char *getBmdFileName();
    static void loadAnmData(J3DModelData *);
    void createModel(JKRSolidHeap *, u32, u32);
    void doUniv();
    void initEquip();
    void callHitItemSound(ItemObj *);
    ItemColFlag calcColReaction(ItemObj *);
    void initDisappear();

    // static J3DAnmObjTrans *mAnmTrans[3];
    // static J3DAnmTransform *mAnmCalc[3];

    virtual ~ItemBananaBig() {} //  0x80254940
};

class ItemFakeItemBox : public ItemBanana
{
public:
    ItemFakeItemBox(u32);
    void reset();
    const char *getBmdFileName();
    static void loadAnmData(J3DModelData *);
    void createModel(JKRSolidHeap *, u32, u32);
    void doUniv();
    void initEquip();
    void callHitItemSound(ItemObj *);
    void moveNormal(CrsGround &);
    ItemColFlag calcColReaction(ItemObj *);
    void initDisappear();
    void doDisappear();
    void calcBaseRotQt();
    void checkKartColDisappear(int);
    void createEfct(const JGeometry::TVec3f &);
    f32 getForceEfctOffsetScale() const;
    void initFall();

    static J3DAnmTextureSRTKey *mAnmTex;
    static J3DAnmTexPattern *sTexPattern;

    virtual ~ItemFakeItemBox() {}          // 0x802547f8
    void createColModel(J3DModelData *) {} // 0x80254918

    u8 _2b0[0x330 - 0x2cc];
};

// Inline Functions referenced in TU:

// virtual AnmController::~AnmController() // AnmController.h; // 0x802518c4
// void AnmControlTrans::changeAnm(u8, bool) // AnmControlTrans.h; // 0x8025202c
// void TAnmControlBase<J3DAnmObjMatTexSRT>::frameProc() // TAnmControlBase.h; // 0x8025409c

#endif // ITEMBANANA_H
