#ifndef ITEMWANWAN_H
#define ITEMWANWAN_H

#include "Sato/ItemObj.h"

// TODO: virtual and static functions(actually, probably everything)
class J3DAnmCluster;

class ItemWanWanObj : public ItemObj
{ // Autogenerated
public:
    ItemWanWanObj(u32);
    void reset();
    const char *getBmdFileName();
    static void loadAnmData(J3DModelData *);
    void getBckName(int);
    void createModel(JKRSolidHeap *, u32, u32);
    void update();
    void drawSimpleModel(u32, Mtx, J3DUClipper *, Mtx);
    void viewCalc(u32);
    void setCurrentViewNo(u32);
    void doUniv();
    ItemColFlag calcColReaction(ItemObj *);
    void initEquip();
    void doEquip();
    void initRelease();
    void setInitReleaseParam();
    void doUnivRelease(bool);
    void doRelease();
    void calcGravity();
    void initDisappear();
    void doDisappear();
    void initFall();
    void doFall();
    void moveNormal(CrsGround &);
    void calcBalanceFlying();
    void initmoveCenterLine();
    void setCLPoint();
    void moveCenterLine();
    void moveStraight();
    void getChainLength();
    void getFirstNodePos(JGeometry::TVec3f *);
    const bool checkKartColDisappear(int);
    void separate();
    void getChainLocatorPos(JGeometry::TVec3f *, Mtx);
    f32 getForceEfctOffsetScale() const;
    void executeGeoObjHitCallBack(GeographyObj *);
    void doTraceEfct();

    static Vec sHandOffsetPos;
    static J3DAnmObjTrans *mAnmTrans[3];
    static J3DAnmTransform *mAnmCalc[3];
    static int sChainJointNo;
    static J3DDeformData *mAnmDeform;
    static J3DAnmCluster *mAnmCluster;

    // Inline/Unused
    void setHitSe();
    void getCenterNodePos(JGeometry::TVec3f *);
    void getLastNodePos(JGeometry::TVec3f *);

    u8 _[0x35c - 0x2b0];
}; 

#endif // ITEMWANWAN_H
