#ifndef ITEMKINOKO_H
#define ITEMKINOKO_H

#include "Sato/ItemSuccession.h"

class ItemKinokoSuc : public ItemObjSuc
{
public:
    ItemKinokoSuc(u32);
    void reset();
    virtual ~ItemKinokoSuc() {} // 0x80255744

    u8 _2b0[0x300 - 0x2b0];
};

class ItemKinoko : public ItemObj
{ // Autogenerated
public:
    ItemKinoko(u32);                            // 0x80254ec4
    void reset();                               // 0x80254f74
    const char *getBmdFileName();               // 0x80254fd8
    void createModel(JKRSolidHeap *, u32, u32); // 0x80255000
    void doUniv();                              // 0x80255004
    void initEquip();                           // 0x802550b0
    void doEquip();                             // 0x802551ac
    void initRelease();                         // 0x802551d8
    void doRelease();                           // 0x802551fc
    void initDisappear();                       // 0x80255200
    void doDisappear();                         // 0x80255218
    void initFall();                            // 0x8025521c
    void executeEquipHandFunc();                // 0x80255258
    // Inline
    virtual ~ItemKinoko() {} // 0x8025538c

    u8 _[0x2b4 - 0x2b0];
}; // class ItemKinoko

class ItemGoldenKinoko : public ItemKinoko
{
public:
    ItemGoldenKinoko(u32);

    void reset();
    const char *getBmdFileName();
    static void loadAnmData(J3DModelData *);
    void createModel(JKRSolidHeap *, u32, u32);
    void doUniv();
    void initRelease();
    void doRelease();
    void initDisappear();
    void update();

    virtual ~ItemGoldenKinoko() {} // 0x8025584c
    void executeEquipHandFunc() {} // 0x80255954
};

#endif // ITEMKINOKO_H
