#ifndef ITEMYOSHIEGG_H
#define ITEMYOSHIEGG_H

#include "JSystem/JGeometry/Vec.h"
#include "Sato/ItemTurtle.h"

// TODO: virtual and static functions

class ItemYoshiEgg : public ItemRTurtle
{ // Autogenerated
public:
    ItemYoshiEgg(u32);                          // 0x8027d9c0
    void reset();                               // 0x8027da54
    const char *getBmdFileName();               // 0x8027dadc
    static void loadAnmData(J3DModelData *);    // 0x8027db04
    void createModel(JKRSolidHeap *, u32, u32); // 0x8027db48
    void update();                              // 0x8027dba8
    void doUniv();                              // 0x8027dbfc
    void initEquip();                           // 0x8027dd9c
    void initRelease();                         // 0x8027df6c
    void initSpRelease();                       // 0x8027dfa0
    void initFall();                            // 0x8027dfd0
    void initDisappear();                       // 0x8027e004
    void doDisappear();                         // 0x8027e3cc
    bool calcRotQuat(Quaternion *);             // 0x8027e3d0
    void calcCreateItem(u32 *);                 // 0x8027e4b4
    u32 calcRndItemKind(u32, u32 *, u32 *);     // 0x8027e620
    ItemColFlag calcColReaction(ItemObj *);     // 0x8027e6cc
    void moveColWall(CrsGround &);              // 0x8027e728
    const bool checkKartColDisappear(int);      // 0x8027e774

    static JGeometry::TVec3f sHandOffsetPos;    // 0x80413888
    static J3DAnmTexPattern *sTexPattern;       // 0x80416d10
    // Inline
    virtual ~ItemYoshiEgg() {}                      // 0x8027e7c0
    const bool checkOver1stKart() { return false; } // 0x8027e918
    void calcGndUpdateQuat() {}                     // 0x8027e920
    void calcFlyingUpdateQuat() {}                  // 0x8027e924

    bool _304;
    bool _305;
    bool _306;
    JGeometry::TVec3f _308;
    J3DAnmObjMaterial mMat; // 314
}; // class ItemYoshiEgg

#endif // ITEMYOSHIEGG_H
