#ifndef ITEMKINOKO_H
#define ITEMKINOKO_H

#include "Sato/ItemSuccession.h"

class ItemKinokoSuc : public ItemObjSuc
{
public:
    ItemKinokoSuc(u32);
    virtual void reset();
    virtual ~ItemKinokoSuc() {} // 0x80255744
};

class ItemKinoko : public ItemObj
{ // Autogenerated
public:
    ItemKinoko(u32);                            // 0x80254ec4

    // Vtable Overrides
    virtual ~ItemKinoko() {}                            // 8
    virtual void reset();                               // 10
    virtual const char *getBmdFileName();               // 28
    virtual void createModel(JKRSolidHeap *, u32, u32); // 40
    virtual void doUniv();                              // 50
    virtual void initEquip();                           // 54
    virtual void initRelease();                         // 58
    virtual void initDisappear();                       // 60
    virtual void initFall();                            // 64
    virtual void doEquip();                             // 78
    virtual void doRelease();                           // 7C
    virtual void doDisappear();                         // 84
    virtual void executeEquipHandFunc();                // AC

    f32 _2b0;
}; // class ItemKinoko

class ItemGoldenKinoko : public ItemKinoko
{
public:
    ItemGoldenKinoko(u32);

    static void loadAnmData(J3DModelData *);
    void update();

    virtual ~ItemGoldenKinoko() {}                                       // 8
    virtual void reset();                                                // 10
    virtual const char *getBmdFileName();                                // 28
    virtual void createModel(JKRSolidHeap *, u32, u32);                  // 40
    virtual void doUniv();                                               // 50
    virtual void initRelease();                                          // 58
    virtual void initDisappear();                                        // 60
    virtual void doRelease();                                            // 7C
    virtual void executeEquipHandFunc() { doHandOneEquip(false, 0.0f); } // AC
};

#endif // ITEMKINOKO_H
