#ifndef RIVALKART_H
#define RIVALKART_H

#include <JSystem/JKernel/JKRDisposer.h>

class KartBody;

class RivalKart
{ // Autogenerated
public:
    // Global
    RivalKart(KartBody *);           // 0x80270f9c
    virtual ~RivalKart();            // 0x8027117c(inline)
    void Init();                     // 0x802711e0
    void StartInit();                // 0x80271228
    static void Reset();             // 0x80271250
    void ResetInit();                // 0x80271274
    void setRankAry();               // 0x802712bc
    void getMaxSpeed() const;        // 0x802712e0
    void getOffsetMaxSpeed() const;  // 0x802712ec
    void setMaxSpeed(const float &); // 0x802712f8
    void ContempLate();              // 0x80271308
    void ActiveCtrl();               // 0x80271398
    // Inline/Unused
    // void InitParam();
    // void getTargetPos(JGeometry::TVec3<float> *);
    // void getVtTargetPos(JGeometry::TVec3<float> *);
    // void getRoadWidth();
    // void DoSearchTarget();

}; // class RivalKart
#endif  // RIVALKART_H