#ifndef INTERP_H
#define INTERP_H

#include "JSystem/JGeometry/Quat.h"
#include "Shiraiwa/Coord3D.h"
#include "JSystem/JGeometry.h"
#include "JSystem/JGeometry/Vec.h"
#include "macros.h"

class TBSplineInterp { // Autogenerated
public:
    TBSplineInterp(); // 0x80290178
    virtual ~TBSplineInterp(); // 0x802901a8
    void init(JGeometry::TVec3f *); // 0x802901f0
    void getVel(JGeometry::TVec3f *); // 0x80290258
    void setPoint(u8, const f32 *, f32, bool); // 0x80290274
    void setPointOffset(u8, const f32 *, f32, bool); // 0x802902cc
    bool update(); // 0x80290354
    bool checkReachTarget(); // 0x80290440
    void updatePos(); // 0x80290490
    void ratioUpdate(); // 0x80290714
    void setRotation(u8); // 0x80290794
    void setSpeed(f32); // 0x8029093c
    void pointUpdate(f32); // 0x80290970
    void stop(); // 0x80290a00
    void restart(); // 0x80290a20
    // Inline/Unused
    void reset();
    void calcPoint(f32);
    void getSamplePoint(u8, u8 *, u8 *);
protected:
    u8 _4;
    u8 _5;
    const f32 *mpPoint; // 8
    f32 mRatio; // c
    s16 _10;
    bool _12;
    bool _13;
    bool _14;
    PLACEHOLDER_BYTES(0x15, 0x18);
    f32 mSpeed;           // 18
    u8 _1c;               //
    TFreeRotate* mRotate; // 20
    JGeometry::TVec3f *mpCurPos; // 24
    JGeometry::TVec3f mOffset; // 28
    JGeometry::TVec3f mVel; // 34
    JGeometry::TQuat4f mPoint;
}; // class Interp
#endif // INTERP_H
