#ifndef MAPOBJDEMOOBJ_H
#define MAPOBJDEMOOBJ_H

#include "Sato/GeographyObj.h"

class TMapObjDemoObj : public GeographyObj { // Autogenerated
public:
    TMapObjDemoObj(const CrsData::SObject &); // 0x802cad44
    TMapObjDemoObj(u32); // 0x802cad9c
    ~TMapObjDemoObj(); // 0x802cadf4

    virtual void reset(); // 0x802cae9c
    virtual void createModel(JKRSolidHeap *, u32); // 0x802caf68
    virtual void calc(); // 0x802cafa0
    virtual void setCurrentViewNo(u32); // 0x802cb11c

    void flagReset(); // 0x802cae84
    void checkKartLength(); // 0x802cb090
    bool checkVisible(); // 0x802cb190
    void turnToKart(); // 0x802cb220
    static const u32 scCameraID[12]; // 0x80385410, firsparkfrondownfarrmontmareitemtoppenddnext
    static f32 sTurnSpeed; // 0x80415478
    // Inline/Unused
    //void scTargetKartRank;
    //void scCheckInterval;
private:
    // TODO
}; // class MapObjDemoObj
#endif // MAPOBJDEMOOBJ_H
