#ifndef MAPOBJHANABI_H
#define MAPOBJHANABI_H

#include "JSystem/JKernel/JKRDisposer.h"
#include "Sato/GeographyObj.h"

class TMapObjHanabi;

// Inline/Unused
//void JSULink<TMapObjHanabi>::~JSULink();
//void JSUList<TMapObjHanabi>::~JSUList();

class THanabiSupervisor : public GeoObjSupervisor {
public:
    THanabiSupervisor();
    ~THanabiSupervisor();
    void entry(TMapObjHanabi *);
    void fire(s16);
    void getFireFrame(s16);
    
    void reset() {} // 0x802cdda0
    void calc() {}  // 0x802cdda4
private:
    JSULink<TMapObjHanabi> mEntryLink;
};

class TMapObjHanabi : public TMapObjHioNode, JKRDisposer { // Autogenerated
public:
    TMapObjHanabi(const CrsData::SObject &); // 0x802cda54

    void reset(); // 0x802cdafc
    void calc(); // 0x802cdb4c

    // ??? GeographyObj::getSupervisor() is a virtual function which this class inherits from (via TMapObjHioNode)
    // and thus this overrides the function in the vtable
    // but is this even valid in C++?
    static THanabiSupervisor *getSupervisor() { return sSupervisor; } 

    static THanabiSupervisor *sSupervisor; // 0x80417110
}; // class MapObjHanabi

#endif // MAPOBJHANABI_H
